### ISSUE TITLE
Game won't run now

### ISSUE THREAD

**Issue by skwizgaar** [SubnauticaModding/QModManager#119]
Installed QMM 3.0 to game directory; game no longer starts. Ran fine with QMM 2.01 

Error message:
Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.

**Comment by PrimeSonic** [comment]
@skwizgaar 
Are you running any third party anti-virus software?

**Comment by skwizgaar** [comment]
avira.  never has been problematic.

**Comment by skwizgaar** [comment]
just reinstalled 2.31 and get the same error (!)

**Comment by skwizgaar** [comment]
there were no errors reported during installation. everything seemed to go well then.

**Comment by PrimeSonic** [comment]
We've had some reports of anti-virus software deleting critical files (that QMM edits).
So far, anyone that has reported issues with QMM has had this in common.

I would strongly encourage you to come to the Discord server where we can troubleshoot with you in real time.
https://discord.gg/UpWuWwq

In the meantime, you can attempt the following steps which recently resolved a similar issue for another player
1. Add Subnautica as an excluded application from Avira scanning
2. Verify your game files to get back to a clean state.
3. Run the [QMM 2.3](https://www.nexusmods.com/subnautica/mods/201?tab=files) installer (it's still available on Nexus)
4. Finally, drop this [DLL](https://github.com/SubnauticaModding/QModManager/blob/master/Build/QModInstaller.dll) in `Subnautica/Subnautica_Data/Managed` (overwrite the one that's already there)

**Comment by skwizgaar** [comment]
i'm couldn't get into discord either !  (everything else DOES work for me, i swear)

**Comment by kylinator25** [comment]
Are you already in 100 discord servers?

**Comment by skwizgaar** [comment]
i've never really used it.  it's forcing me to "claim my account", then won't allow me to, as my email address is already registered.

**Comment by skwizgaar** [comment]
most days go much better than this, really ! LOL

**Comment by skwizgaar** [comment]
so, i reinstalled the game, and it ran - with no mods showing.  ran the 2.31 installer, and it killed it again.  is there an older version that i can use somewhere ?

**Comment by MrPurple6411** [comment]
what version of the game are you trying to run?

**Comment by skwizgaar** [comment]
mine must be old.  turns out that just running your 2.02 installer fixes everything in this case.

**Comment by kylinator25** [comment]
What platform do you own the game on?

**Comment by AlexejheroYTB** [comment]
@skwizgaar Are you on Subnautica or Below Zero and what platform do you own the game on?

**Comment by AlexejheroYTB** [comment]
Not a bug. Next time don't pirate the game
