### ISSUE TITLE
Make the installation work on Linux properly

### ISSUE THREAD

**Issue by Gaming4LifeDE** [SubnauticaModding/QModManager#135]
**Describe the problem**
I've tried to get QModManager to install for hours by now and it just doesn't work, the installer breaks (stuck at "finishing installation" while an error is spit out on the terminal). Is there a way to make a manual install for this?

**Comment by AlexejheroYTB** [comment]
What is the error in the terminal?

**Comment by Gaming4LifeDE** [comment]
```
Installing QModManager...
EXCEPTION CAUGHT!
System.MissingMethodException: Method not found: !!0 System.Linq.Enumerable.Single<!0>(System.Collections.Generic.IEnumerable`1<!!0>,System.Func`2<!!0, bool>)
  at QModManager.Executable.Main (System.String[] args) [0x001ff] in <d655c87dedf24304a40a4af0cbcea5df>:0 

0035:fixme:console:CONSOLE_DefaultHandler Terminating process 24 on event 0
0033:fixme:console:CONSOLE_DefaultHandler Terminating process 2f on event 0
0034:fixme:console:CONSOLE_DefaultHandler Terminating process 2b on event 0
0034:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded.
0033:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded.
```

**Comment by Gaming4LifeDE** [comment]
Also, there should really be a proper tutorial on how to install it on Linux too. The installer is a bit finicky too (no HiDPI scaling, clicking browse when searching for a path and then setting one just makes the installer window vanish completely)

**Comment by AlexejheroYTB** [comment]
QModManager theoretically doesn't support either Mac or Linux. We just have some basic instructions that other people using have added.

**Comment by AlexejheroYTB** [comment]
The error seems weird, do you have .NET Framework 3.5 installed?

**Comment by Gaming4LifeDE** [comment]
Well this is running inside of Proton so just whatever the default is.

Do you plan on supporting Linux through Proton? I think you'd only need to change a few things but not much.

**Comment by alaestor** [comment]
AFAIK .NET 3.5 doesn't play well with wine. There is a winetricks script for "dotnet30" which (sometimes) installs depending on distro but it's quite borked and will throw a plethora of "fixme" errors.

Regardless of method - proton or otherwise - I still get "Runtime error (at 56:357): Unknown method."

I'm still quite new to linux and wine, so maybe I'm missing something; but so far I've been unable to get it working. It's a shame there's no official cross-platform installation tools, or manual installation guide...

**Comment by Gaming4LifeDE** [comment]
@AlexejheroYTB ist Dotnet 3.5 Just a dependency of the installer or what are you using it for?

If not, would you consider porting to mono? (Should be pretty easy to do I think)

**Comment by AlexejheroYTB** [comment]
Mac and Linux support is not official yet. None of us have mac or linux systems, so unfortunately we can't help you.
