### ISSUE TITLE
Mac installer & files not working with current Unity & Subnautica version

### ISSUE THREAD

**Issue by WWWFWWW** [SubnauticaModding/QModManager#137]
The provided Mac files and installer seem to be from May 2019 (QModManager ver. 2.1), which is per release notes incompatible with current game and Unity version (QModManager ver. 3.01), could that be the culprit? Tried manual install per instructions (copying from Build and Dependencies dirs), that did not work either (Mono 6.8 Stable). Subnautica from Epic Games, ver. 63668. 

Manual install from 2.1 Mac folder sort of worked (mono QModManager.exe ran ok), but game crashed upon launching (old Unity dlls?).

Manual install from Build and Dependencies dirs did not work (mono QModManager.exe resulter in errors).

**Comment by AlexejheroYTB** [comment]
The mac and linux files have not been updated for the latest version. Until the creator of these files decides to update them, we've removed them from this repo.
**Mac and Linux support is not official yet**
