### ISSUE TITLE
Runtime error at 56:357 trying to install

### ISSUE THREAD

**Issue by kr6k3n** [SubnauticaModding/QModManager#139]
**Describe the bug**

Runtime error at 55:357 trying to install with the latest version dowloaded at Nexus Mods
**Screenshots**

![image](https://user-images.githubusercontent.com/52788711/79066447-4152e600-7cb8-11ea-9925-3729c562d1a1.png)
it's french for invalid namespace

**Comment by AlexejheroYTB** [comment]
This is a known issue.
To fix it, you need to repair windows management instrumentation: http://www.mediafire.com/file/c4cy2qd5ldb12fp/RepairWMI.zip/file

**Comment by kr6k3n** [comment]
Thank you so much!
