### ISSUE TITLE
Subnautica BZ will not run stuck on black loading screen

### ISSUE THREAD

**Issue by mtxxtcy** [SubnauticaModding/QModManager#153]
It will not let me launch Subnautica BZ. with Qmods installed , it will open to a black loading screen, the game runs fine without Qmod but as soon as qmods is installed it wont load. I've uninstalled and reinstalled the game and Qmods, both seem to not do anything. I've changed the name to Qmods1 as the folder name and it worked but then none of the mods would work in the game.  So i read on you mod page that every update you need to reinstall the QMods and i did as such and still nothing, it will not let me play the game with the Qmod installed. if you could please help me id very much appreciate it. i can play in the original Subnautica with no issues but i feel since BZ is still under development there has to be an issue going on. 

thank you very much! hope to hear from you soon!

**Comment by AlexejheroYTB** [comment]
Known issue.

**Comment by mtxxtcy** [comment]
> Known issue.

any solutions?

**Comment by PrimeSonic** [comment]
Known issue. Update is in progress. https://github.com/SubnauticaModding/QModManager/pull/152
