### ISSUE TITLE
still not working after update to 3.3 BZ 

### ISSUE THREAD

**Issue by mtxxtcy** [SubnauticaModding/QModManager#154]
same issue. mods will not run on Qmods when it did open and then i uninstalled and reinstalled the game and qmods and still no good even after the 3.3 update? idk if i'm doing something wrong, but i have done the same thing i did with Subnautica and it works fine and  with BZ its no good,

**Comment by PrimeSonic** [comment]
https://www.nexusmods.com/subnauticabelowzero/mods/1?tab=files
![image](https://user-images.githubusercontent.com/39146191/86082056-e930b200-ba64-11ea-9c9c-d940347d36ce.png)

**Comment by mtxxtcy** [comment]
that is what i downloaded was the experimental version.

**Comment by mtxxtcy** [comment]
![image](https://user-images.githubusercontent.com/67552812/86083427-1a05ec80-ba4f-11ea-8aef-72396455ef98.png)

**Comment by kylinator25** [comment]
It means the experimental branch of Subnautica: Below Zero, on Steam, right click the game, go to Properties > Betas and select the experimental version. The game will update, then reinstall QModManager once that is finished.
