### ISSUE TITLE
Version dependencies: 2.8 != 2.8.0

### ISSUE THREAD

**Issue by tobeyStraitjacket** [SubnauticaModding/QModManager#160]
**Describe the bug**
When checking version dependencies, 2.8 is not considered equal to 2.8.0. Therefore, if SMLHelper's version is set to "2.8" and another mod specifies a version dependency of `"SMLHelper": "2.8.0"`, QMM considers the `2.8` version to be older than `2.8.0` due to a quirk of `Version` in .NET:
https://docs.microsoft.com/en-us/dotnet/api/system.version.compareto?view=netcore-3.1

We probably need to just clean the version strings before we parse them, trim any occurrences of ".0" from the end.

**Comment by PrimeSonic** [comment]
@tobeyStraitjacket  Is this issue good to close or was there more needed on the BepInEx side?

**Comment by tobeyStraitjacket** [comment]
> @tobeyStraitjacket Is this issue good to close or was there more needed on the BepInEx side?

Yeah I would say we're all good now.

**Comment by PrimeSonic** [comment]
Closing as this change has been released
