### ISSUE TITLE
Add logs location

### ISSUE THREAD

**Issue by K07H** [SubnauticaModding/QModManager#161]
**Suggestion**
Add following line on "Logger" page to tell where is the logs output:
`Logs will be written to the default Subnautica log file (%userprofile%\AppData\LocalLow\Unknown Worlds\Subnautica\Player.log).`

**Comment by AlexejheroYTB** [comment]
Perhaps the log path outputted by BepInEx? Also btw, @tobeyStraitjacket, this should also be updated in the Dialog class for the See Log button.

**Comment by tobeyStraitjacket** [comment]
> Perhaps the log path outputted by BepInEx? Also btw, @tobeyStraitjacket, this should also be updated in the Dialog class for the See Log button.

Yeah I would point them to `[gamedir]\qmodmanager_log-[name of game].txt`:
![image](https://user-images.githubusercontent.com/45315526/89354712-7cd34f00-d6b1-11ea-8fc4-c8dc430f243b.png)

And yeah, I'll look at updating the dialog class, good shout.

**Comment by PrimeSonic** [comment]
Should probably also be included in the basic `README.md` file,  
probably near the top where players can see it.
