### ISSUE TITLE
4.0 won't work, other versions break the game

### ISSUE THREAD

**Issue by fcukurmomed** [SubnauticaModding/QModManager#162]
Installing 4.0 doesn't create QMods folder, if i create it myself no mods work. Other versions simply corrupt game files:

(Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.)

**Comment by AlexejheroYTB** [comment]
Are you using a pirated version of Subnautica?

**Comment by fcukurmomed** [comment]
yes

**Comment by AlexejheroYTB** [comment]
We don't support cracked versions.

**Comment by fcukurmomed** [comment]
ehh, then go kill urself faggot
