### ISSUE TITLE
Add information for installing QMods on Linux with Steam Play Proton

### ISSUE THREAD

**Issue by waterlubber** [SubnauticaModding/QModManager#173]
Modding Subnautica & Subnautica: Below Zero is very much possible and can be achieved with very little work! follow the instructions below on how to properly setup a modded environment.

# Installing QMods on Linux with Proton

1. Right click on Subnautica, select `Manage` then `Browse local files`
2. Manually download the ZIP archive of QModManager from here: [https://www.nexusmods.com/subnautica/mods/201?tab=files](https://www.nexusmods.com/subnautica/mods/201?tab=files)
3. Extract the files directly to the folder opened in step 1 - if you've done it correctly you should see a file called `winhttp.dll`
4. Right click on Subnautica in your library, select `Properties` and add this to the launch options:
```
WINEDLLOVERRIDES='winhttp.dll=n,b' %command%
```
5. Now you should have a `QMods` folder in your Subnautica folder. Simply put your mods in that folder and they will load to the game!

## Troubleshooting:
- If there's no `QMods` folder in your Subnautica root folder after installing QModManager, create a folder named `QMods` manually yourself.
 - Most mods require [SMLHelper](https://github.com/SubnauticaModding/SMLHelper/releases/) to work. Make sure to install it as well and pay attention to the dependencies of any mod you're installing.
 - Ensure you are using the latest version of Subnautica or Below Zero. Modding experimental builds is unreliable and often very buggy, make sure to mod the stable build of the games instead. 
 
 
Credits to @szszoke for writing this simple version of the required instructions.

**Comment by BodhiChiron** [comment]
Thanks!! It worked for me. Used dotnet40 as well. Got a lot of warnings because of using x64 wine but works nonetheless. Did take more than an hour of trying things out..

**Comment by saxyomega90125** [comment]
I needed an extra step - after I ran the QmodManager installer and did the winecfg thing Qmods' stuff still wouldn't show in-game - but I did get it working. If you're having problems, try this.
First, you need dotnet40, not dotnet35. As BodhiChiron said, lots of errors and warnings about 64-bit architecture, and I also get two warnings about run32dll.exe or some such every time I open up Subnautica's Wine prefix, but it seems to work fine. The other bit about adding dll overrides in winecfg is important - that was not mentioned in the Linux installation guide on QMM's Nexus Mods page, which is why I'm here!
As I said, that still failed though, so in my troubleshooting I found that BepInEx never generated a config so I believe it never initialized. I went and got BepInEx from its Github distribution (url in OP - you need **x64 Windows**, not the Unix-like version), and I extracted it and overwrote the BepInEx components that shipped with QModManager. _That_ got Qmods working.
Cyclops Near Field Sonar and Prawnsuit Volumetric Lights both fail to initialize, even alone, I am guessing because they include source code (why do modders do that...?). But all the other mods I have tried seem to work properly, including the all-important More Quick Slots and Prawn Lightswitch.
I'm running Kubuntu 20.04, and Steam installed from their own Debian installer. I initially used Proton 5.0-10, but 5.13-1 also works, and the game doesn't seem to care either way.

**Comment by BodhiChiron** [comment]
Now trying to install QmodManager for Below Zero. Will edit this comment with my findings.
First off, regarding 3. wineprefix: the pfx for Below Zero is 848450  (protontricks will recognize this)
Dotnet40 is necessary, so install winetricks and protontricks and use protontricks:
choose "select the default wineprefix", now choose "install a windows dll or component", choose dotnet40
press ok for several 64bit warnings (i counted 6!) and wait a bit while it downloads and installs
Now you should get the microsoft dotnet 4.0 installer, continue..
This is where i got stuck with Below Zero, the dotnet installer froze on this error:
0568:err:ole:CoReleaseMarshalData StdMarshal ReleaseMarshalData failed with error 0x8001011d
062c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
062c:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
062c:fixme:process:SetProcessDEPPolicy (1): stub
062c:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0600:err:ole:CoGetContextToken apartment not initialised
062c:fixme:path:parse_url failed to parse L"System"
062c:fixme:process:FlushProcessWriteBuffers : stub

Will try again later..

**Comment by hlriffel** [comment]
I was able to get QModManager installed and trying to load the mods when starting the game after installing dotnet40 and overriding the `winhttp` DLL. However, everytime QMod tries to load any of the mods, I get a BadImageFormatException referring to the mod's DLL (QMods/Modding Helper/SMLHelper.dll, for example). I'm using Manjaro KDE and Proton GE 6.5-2.

This is the log if anyone is facing the same issue: https://pastebin.com/XgyVUnDi

Unfortunately, I haven't found any solution yet.

**Comment by wilbowma** [comment]
> I was able to get QModManager installed and trying to load the mods when starting the game after installing dotnet40 and overriding the `winhttp` DLL. However, everytime QMod tries to load any of the mods, I get a BadImageFormatException referring to the mod's DLL (QMods/Modding Helper/SMLHelper.dll, for example). I'm using Manjaro KDE and Proton GE 6.5-2.
> 
> This is the log if anyone is facing the same issue: https://pastebin.com/XgyVUnDi
> 
> Unfortunately, I haven't found any solution yet.
I had this problem and solved it.

When opening some mods zip files in Ark, there was no folder. Instead, the files were named something like `Modding Helper\mod.json`, `Modding Helper\SMLHelper.dll`. That is, the folder name seemed to get turned into part of the file name.

The solution was to manually create the folder in `QMod`, move the files there, and rename the files to remove everything before the backslash.

**Comment by hlriffel** [comment]
> > I was able to get QModManager installed and trying to load the mods when starting the game after installing dotnet40 and overriding the `winhttp` DLL. However, everytime QMod tries to load any of the mods, I get a BadImageFormatException referring to the mod's DLL (QMods/Modding Helper/SMLHelper.dll, for example). I'm using Manjaro KDE and Proton GE 6.5-2.
> > This is the log if anyone is facing the same issue: https://pastebin.com/XgyVUnDi
> > Unfortunately, I haven't found any solution yet.
> 
> I had this problem and solved it.
> 
> When opening some mods zip files in Ark, there was no folder. Instead, the files were named something like `Modding Helper\mod.json`, `Modding Helper\SMLHelper.dll`. That is, the folder name seemed to get turned into part of the file name.
> 
> The solution was to manually create the folder in `QMods`, move the files there, and rename the files to remove everything before the backslash.

I was finally able to solve this issue as well. Apparently the issue was indeed related to Ark, but the problem was a little bit deeper than just the file names. It seems that, when unzipping the files using Ark, it was somehow altering the contents of the DLLs, which later caused them to be in a bad format, hence the BadImageFormatException. Unzipping the mods using `unzip` fixed this all the issues for me.

I am so happy to finally be able to play this awesome game with mods. Thank you all for writing this info on how to make it work on Linux :slightly_smiling_face:

**Comment by kiven7e** [comment]
when i ran "WINEPREFIX=~/.local/share/Steam/steamapps/compatdata/848450/pfx/ wine /home/kiven/Downloads/QModManager.exe" in the terminal i got a bunch of errors https://pastebin.com/DPvH2CVh on Debian bullseye

**Comment by lordcirth** [comment]
While I got this working a year or so ago, I can't get it to work now. I'm on NixOS. I installed dotnet40 (after many false starts) and ran the installer, and it created an empty QMods directory. The installer did look pretty janky, and when selecting the Subnautica game directory, I got an error popup saying "Could not call proc". But it seemed to complete fine after that.

But, starting Subnautica, there is no Mods tab under Settings. I don't know what is wrong or where to look. I don't see any logs. Tried PROTON_LOG=1 (with grep -v "RtlGrowFunctionTable", as that spam was the bulk of it).

[SubnauticaProton.log](https://github.com/SubnauticaModding/QModManager/files/6567516/SubnauticaProton.log)

Thanks.
@hlriffel @wilbowma

**Comment by hlriffel** [comment]
> While I got this working a year or so ago, I can't get it to work now. I'm on NixOS. I installed dotnet40 (after many false starts) and ran the installer, and it created an empty QMods directory. The installer did look pretty janky, and when selecting the Subnautica game directory, I got an error popup saying "Could not call proc". But it seemed to complete fine after that.
> 
> But, starting Subnautica, there is no Mods tab under Settings. I don't know what is wrong or where to look. I don't see any logs. Tried PROTON_LOG=1 (with grep -v "RtlGrowFunctionTable", as that spam was the bulk of it).
> 
> [SubnauticaProton.log](https://github.com/SubnauticaModding/QModManager/files/6567516/SubnauticaProton.log)
> 
> Thanks.
> @hlriffel @wilbowma

@lordcirth 

Did you execute `winecfg` and added `winhttp` as an overridden library?

**Comment by lordcirth** [comment]
@hlriffel Yes, I overrode `winhttp` and `version`

**Comment by Termuellinator** [comment]
I'm currently trying to get things to work, but with no luck - i was able to install QMM with `dotnet40` (hat to use `WINE=$(which wine) protontricks 264710 dotnet40` to get it to install without an error), `win7`, `winhttp` + `version` overrides, the QMods and BepInEx folders are created in the gamefolder, but when i load the game i see no sign of the mods being active, neither in settings menu nor ingame :/

**Comment by RobertLSnead** [comment]
it fails to install no matter what I try, looks like it's checking for a windows environment when trying to run the new installer.
qmodinstaller will just not work with the current steps posted.
anyone have any updated instructions?

**Comment by RobertLSnead** [comment]
> when i ran "WINEPREFIX=~/.local/share/Steam/steamapps/compatdata/848450/pfx/ wine /home/kiven/Downloads/QModManager.exe" in the terminal i got a bunch of errors https://pastebin.com/DPvH2CVh on Debian bullseye

Same issue on my end, nothing works for me

**Comment by Nyloseth** [comment]
Thank you for this, it still works when following the directions to a T.

**Comment by sparky8251** [comment]
Same for me. Wish this was easier to find as it was several days of on and off searching until I found this.

**Comment by szszoke** [comment]
There is a much simpler way to do this than what is described in the issue:

1. Right click on Subnautica, select `Manage` then `Browse local files`
2. Manually download the ZIP archive of QModManager from here: [https://www.nexusmods.com/subnautica/mods/201?tab=files](https://www.nexusmods.com/subnautica/mods/201?tab=files)
3. Extract the files directly to the folder opened in step 1 - if you've done it correctly you should see a file called `winhttp.dll`
4. Right click on Subnautica in your library, select `Properties` and add this to the launch options:
```
WINEDLLOVERRIDES='winhttp.dll=n,b' %command%
```

There should be a folder called `QMods` in the folder that you opened in step 1. That is where you put your mods. Create one if it is missing.

I tested this on a Steam Deck in Desltop Mode, where I had no access to `winecfg` and doing anything in the terminal was just annoying.

**Comment by Perodactyl** [comment]
> 

This works for me (QmodLoader is clearly running) but I immediately get a red popup saying that every mod is failing with some "harmony" extenssion file or simething from bepinex (I don't really understand it)
Pastebin: https://pastebin.com/raw/AV3X0VLV

**Comment by szszoke** [comment]
Indeed there many log entries complaining about SMLHelper missing.

I in the meantime successfully tested my method with Below Zero. Just make sure to download the correct edition of QModManager.

**Comment by Metious** [comment]
There's also the [Running games on Steam](https://docs.bepinex.dev/articles/advanced/steam_interop.html?tabs=tabid-1) article provided by BepInEx which also has the instructions on how to setup Unity games to run mods. Follow them after extracting QModManager to your game root folder and let me know if they're more straight forward.

@szszoke's instructions also look promising. Unfortunately at the meantime none of QModManager devs have a Linux machine so we cant confirm the best method to do this. We are however, looking for the most successful method to update this issue with.

**Comment by METDeath** [comment]
> There is a much simpler way to do this than what is described in the issue:
> 
> 1. Right click on Subnautica, select `Manage` then `Browse local files`
> 2. Manually download the ZIP archive of QModManager from here: https://www.nexusmods.com/subnautica/mods/201?tab=files
> 3. Extract the files directly to the folder opened in step 1 - if you've done it correctly you should see a file called `winhttp.dll`
> 4. Right click on Subnautica in your library, select `Properties` and add this to the launch options:
> 
> ```
> WINEDLLOVERRIDES='winhttp.dll=n,b' %command%
> ```
> 
> There should be a folder called `QMods` in the folder that you opened in step 1. That is where you put your mods. Create one if it is missing.
> 
> I tested this on a Steam Deck in Desltop Mode, where I had no access to `winecfg` and doing anything in the terminal was just annoying.

THANK YOU!!!

**Comment by Metious** [comment]
I can confirm that @szszoke's instructions work consistently. Updated this issue to point to your instructions.
Thank you for sharing it!

**Comment by PrimeSonic** [comment]
Found that Lutris also has a runner to install the game with mod support.
https://lutris.net/games/subnautica/

**Comment by zyxer** [comment]
I'm trying to run Subnautica Below Zero on a brand new Steam Deck with mods (Map mod) using instructions provided by @szszoke. I got no luck, the game freezes on the warning screen with the main menu sounds in the background. In `qmodmanager_log-SubnauticaZero.txt` I see two errors:
1) `System.TypeLoadException: Could not load type SentrySdk, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)`
2) `InvalidOperationException: Steamworks is not initialized.` 

Not sure which one is critical. Here's a link to the full log: https://pastebin.com/paYxpvcz

**Comment by Metious** [comment]
> I'm trying to run Subnautica Below Zero on a brand new Steam Deck with mods (Map mod) using instructions provided by @szszoke. I got no luck, the game freezes on the warning screen with the main menu sounds in the background. In `qmodmanager_log-SubnauticaZero.txt` I see two errors:
> 
> 1. `System.TypeLoadException: Could not load type SentrySdk, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)`
> 2. `InvalidOperationException: Steamworks is not initialized.`
> 
> Not sure which one is critical. Here's a link to the full log: https://pastebin.com/paYxpvcz

This is due to the latest Below Zero "What The Dock Update", which broke QModManager and isn't related to the linux instructions.

Join the [Subnautica Modding Discord Server](https://discord.gg/UpWuWwq) and you can find the fixed builds there.

**Comment by desperationfighter** [comment]
We are aware of this issue and and it is not related to Steam Deck. As can see on the Commits and Pull request we already in action to fix everything related to the last BZ Update that was just puiblished only some hours ago.
That also means we have already a available BETA ready to test.

https://discord.gg/UpWuWwq Join here and visit the Modding news channel. if you have still issues with the beta visit the help channels there thats faster and easier than github.
