### ISSUE TITLE
QModManager 4 doesn't install properly

### ISSUE THREAD

**Issue by wiblesss** [SubnauticaModding/QModManager#188]
When i tried to install QModManager 4 it doesn't install properly, the QMod folder appeared, but none of the Qmod files have shown up in C:\SteamLibrary\steamapps\common\Subnautica\Subnautica_Data\Managed

![subnautica qmod](https://user-images.githubusercontent.com/71091471/92777627-3aa6c880-f355-11ea-90ff-e182848a25fc.png)

QModManager 3 works just not QModManager 4
(I already have tried doing the map mod but it didn't work)

**Comment by AlexejheroYTB** [comment]
QModManager 4 doesn't touch the managed folder anymore. All of the QMM files are in the BepInEx folder

**Comment by wiblesss** [comment]
i saw the QMM files in there but the mod tab in options doesn't appear and any mods don't work. Any idea why?

**Comment by PrimeSonic** [comment]
> i saw the QMM files in there but the mod tab in options doesn't appear and any mods don't work. Any idea why?
More than likely you have edited files leftover from a previous mod loader installation.

You can try deleting all files in the Managed folder and re-downloading them via Steam's [Verify Integrity Check](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335).  
That should resolve it.

If you have further issues, you can get help in the Subnautica Modding Discord https://discord.gg/UpWuWwq

**Comment by wiblesss** [comment]
It Worked. thank :D
