### ISSUE TITLE
Relicts of the Past update broke mod options

### ISSUE THREAD

**Issue by Zemogiter** [SubnauticaModding/QModManager#197]
**Describe the issue**
Upon entering mod tab in game options I receive this error:
```
MissingMethodException: uGUI_SnappingSlider uGUI_TabbedControlsPanel.AddSliderOption(int,string,single,single,single,single,single,UnityEngine.Events.UnityAction`1<single>,SliderLabelMode)
  at SMLHelper.V2.Options.ModOptions+<>c__DisplayClass26_0.<AddOptionsToPanel>b__0 (SMLHelper.V2.Options.ModOption option) [0x00000] in <3ab16902b00c48189741143d09f273df>:0 
  at SystemExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] items, System.Action`1[T] action) [0x00010] in <a273d96341f140c18bc60540f9e633cb>:0 
  at SMLHelper.V2.Options.ModOptions.AddOptionsToPanel (uGUI_TabbedControlsPanel panel, System.Int32 tabIndex) [0x00047] in <3ab16902b00c48189741143d09f273df>:0 
  at SMLHelper.V2.Patchers.OptionsPanelPatcher+<>c__DisplayClass4_0.<AddTabs_Postfix>b__1 (SMLHelper.V2.Options.ModOptions options) [0x00000] in <3ab16902b00c48189741143d09f273df>:0 
  at SystemExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] items, System.Action`1[T] action) [0x00010] in <a273d96341f140c18bc60540f9e633cb>:0 
  at SMLHelper.V2.Patchers.OptionsPanelPatcher.AddTabs_Postfix (uGUI_OptionsPanel __instance) [0x0012c] in <3ab16902b00c48189741143d09f273df>:0 
  at (wrapper dynamic-method) uGUI_OptionsPanel.DMD<uGUI_OptionsPanel::AddTabs>(uGUI_OptionsPanel)
  at uGUI_OptionsPanel.OnEnable () [0x0002d] in <f6fd98deb9ff41358c10ee40c13c0a7a>:0 
UnityEngine.GameObject:SetActive(Boolean)
MainMenuRightSide:OpenGroup(String)
uGUI_MainMenu:OnButtonOptions()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
FPSInputModule:ProcessMousePress(MouseButtonEventData)
FPSInputModule:ProcessMouseEvent()
FPSInputModule:OnUpdate()
ManagedUpdate:Execute(Queue)
ManagedUpdate:LateUpdate()
```
And the slider dosen't show up.

**Additional info**
Full log:
[Player.log](https://github.com/SubnauticaModding/QModManager/files/5476814/Player.log)
[qmodmanager_log-SubnauticaZero.txt](https://github.com/SubnauticaModding/QModManager/files/5476816/qmodmanager_log-SubnauticaZero.txt)
List of mods:
- https://www.nexusmods.com/subnauticabelowzero/mods/110
- https://www.nexusmods.com/subnauticabelowzero/mods/106
- https://www.nexusmods.com/subnauticabelowzero/mods/105
- https://www.nexusmods.com/subnauticabelowzero/mods/104
- https://www.nexusmods.com/subnauticabelowzero/mods/103
- https://www.nexusmods.com/subnauticabelowzero/mods/101
- https://www.nexusmods.com/subnauticabelowzero/mods/98
- https://www.nexusmods.com/subnauticabelowzero/mods/95
- https://www.nexusmods.com/subnauticabelowzero/mods/44
- https://www.nexusmods.com/subnauticabelowzero/mods/92
- https://www.nexusmods.com/subnauticabelowzero/mods/90
- https://www.nexusmods.com/subnauticabelowzero/mods/91
- https://www.nexusmods.com/subnauticabelowzero/mods/86
- https://www.nexusmods.com/subnauticabelowzero/mods/84
- https://www.nexusmods.com/subnauticabelowzero/mods/84
- https://www.nexusmods.com/subnauticabelowzero/mods/82
- https://www.nexusmods.com/subnauticabelowzero/mods/76
- https://www.nexusmods.com/subnauticabelowzero/mods/75
- https://www.nexusmods.com/subnauticabelowzero/mods/73
- https://www.nexusmods.com/subnauticabelowzero/mods/67
- https://www.nexusmods.com/subnauticabelowzero/mods/64
- https://www.nexusmods.com/subnauticabelowzero/mods/58
- https://www.nexusmods.com/subnauticabelowzero/mods/57
- https://www.nexusmods.com/subnauticabelowzero/mods/51
- https://www.nexusmods.com/subnauticabelowzero/mods/48
- https://www.nexusmods.com/subnauticabelowzero/mods/27
- https://www.nexusmods.com/subnauticabelowzero/mods/26
- https://www.nexusmods.com/subnauticabelowzero/mods/25
- https://www.nexusmods.com/subnauticabelowzero/mods/18
- https://www.nexusmods.com/subnauticabelowzero/mods/17
- https://www.nexusmods.com/subnauticabelowzero/mods/15
- https://www.nexusmods.com/subnauticabelowzero/mods/10
- https://www.nexusmods.com/subnauticabelowzero/mods/9

**Comment by PrimeSonic** [comment]
1. We have known about this since the day the update was released. You are 4 days late.
2. This is an issue is from SMLHelper, not QModManager, and we are already working on a fix https://github.com/SubnauticaModding/SMLHelper/pull/195

We already have an open beta in testing, which you would have known about if you were actually involved in the Subnautica Modding community.

Closing.
