### ISSUE TITLE
Win10 Unhandled Exception

### ISSUE THREAD

**Issue by inetbiz** [SubnauticaModding/QModManager#198]
**Describe the bug**
Qmod will not initialize

**Screenshots**

![image](https://user-images.githubusercontent.com/3696477/98569838-c15a2200-2280-11eb-9e0b-f209015b1866.png)

**Additional info**
Couldn't find anything, specific, in event manager. Unless, it's buried?

**Comment by PrimeSonic** [comment]
You don't need to be reporting a bug. You need technical support to help fix your game files and/or mod loadout.

You can get help with this over in the Subnautica Modding Discord.
https://discord.gg/UpWuWwq
