### ISSUE TITLE
Not enabled since last stream update

### ISSUE THREAD

**Issue by xuefer** [SubnauticaModding/QModManager#203]
**Describe the bug**
after stream updated, no longer work

verified with procexp dll handlers view:
launching Subnautica Below Zero load all necessary dlls in BepInEx/* but then Subnautica restarts itself under stream. SubnauticaZero/winhttp.dll got loaded but nothing get loaded from BepInEx

**Comment by PrimeSonic** [comment]
We do not offer support over GitHub.
Please visit the Subnautica Modding Discord server for assistance
https://discord.gg/UpWuWwq
