### ISSUE TITLE
No mod menu or any functionality

### ISSUE THREAD

**Issue by NCL98** [SubnauticaModding/QModManager#206]
I have tried instaling Qmods and the Map mod several times now and, while it work on my other computer, I cannot run it on this one. The mod tab in options never shows up and the mods I put into the folder just do not function. I shall attach the log file if it helps

Pastebin link for log: https://pastebin.com/7a1hLZN6

**Comment by PrimeSonic** [comment]
There are a number of things specific to your system that can cause the mod loader to fail.

We do not offer support via GitHub issues.
If you need assistance, please visit the Subnautica Modding Discord server https://discord.gg/UpWuWwq
