### ISSUE TITLE
Problem with xbox game pass

### ISSUE THREAD

**Issue by Dagand2016** [SubnauticaModding/QModManager#209]
**Describe the problem**

i have xbox game pass and i play  subnautica in my PC and i want install QmodManager but windows blocked folder where the game is installed. What i can do?

**Screenshots**

**Additional info**

**Comment by desperationfighter** [comment]
Hi,

Modding on XBox Game Pass is a little bit tricky.
There is a Manual over there in the Subnautica Modding Discord for this case.
I would recommend you to join: https://discord.gg/UpWuWwq

Also Error Handling is much easier on a life chat.
