### ISSUE TITLE
Crash when starting game 

### ISSUE THREAD

**Issue by svenMOrd** [SubnauticaModding/QModManager#210]
Clean install from steam, then install qmodmanager 

got the following error:  
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Subnautica/Subnautica_Data/Mono/data-0000026F2373E360.dll
Initialize engine version: 2019.4.9f1 (630)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Subnautica/Subnautica_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version:  Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
Vendor:
VRAM:     11127 MB
Driver:   27.21.14.5709
Begin MonoManager ReloadAssembly
- Completed reload, in  0.144 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed 
(Filename:  Line: 369)
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.

[Message:   BepInEx] BepInEx 5.4.5.0 - Subnautica
[Info   :   BepInEx] Running under Unity v2019.4.9.630
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.0.2.6]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.0.2.6]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Fatal  :QModPluginGenerator] An exception occurred while attempting to generate BepInEx PluginInfos: Could not resolve type with token 01000025 (from typeref, class/assembly Oculus.Newtonsoft.Json.Bson.BsonReader, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null).
[Fatal  :QModPluginGenerator] Beginning stacktrace:
[Fatal  :QModPluginGenerator]   at QModManager.QModPluginGenerator.GetPluginCache () [0x00000] in <773766e20f9a4863a8c37f9f0e678d84>:0 
  at QModManager.QModPluginGenerator.Finish () [0x00000] in <773766e20f9a4863a8c37f9f0e678d84>:0
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [QMMLoader 1.0]
[Message:   BepInEx] Chainloader startup complete
UnloadTime: 0.585800 ms
AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Unloading 4 Unused Serialized files (Serialized files now loaded: 9)
UnloadTime: 3.200500 ms
[QModManager:INFO] Detected game: Subnautica
[QModManager:INFO] Game Version: 67522 Build Date: 01-February-2021
[QModManager:INFO] Loading QModManager v4.0.2.6...
[QModManager:INFO] Today is 01-February-2021
[QModManager:INFO] Folder structure:
+ Subnautica
|---+ BepInEx
|   |---+ cache
|   |   |---- chainloader_typeloader.dat (346.00B)
|   |   `---- harmony_interop_cache.dat (705.00B)
|   |---+ config
|   |   |---- BepInEx.cfg (4.88KB)
|   |   `---- MirrorInternalLogs.cfg (788.00B)
|   |---+ core
|   |   |---- 0Harmony.dll (174.00KB)
|   |   |---- 0Harmony.xml (240.57KB)
|   |   |---- 0Harmony109.dll (42.00KB)
|   |   |---- 0Harmony12.dll (66.00KB)
|   |   |---- 0Harmony20.dll (109.00KB)
|   |   |---- BepInEx.dll (108.50KB)
|   |   |---- BepInEx.Harmony.dll (5.50KB)
|   |   |---- BepInEx.Harmony.xml (3.96KB)
|   |   |---- BepInEx.Preloader.dll (40.50KB)
|   |   |---- BepInEx.Preloader.xml (7.52KB)
|   |   |---- BepInEx.xml (82.72KB)
|   |   |---- HarmonyXInterop.dll (23.00KB)
|   |   |---- Mono.Cecil.dll (331.50KB)
|   |   |---- Mono.Cecil.Mdb.dll (42.00KB)
|   |   |---- Mono.Cecil.Pdb.dll (84.50KB)
|   |   |---- Mono.Cecil.Rocks.dll (27.00KB)
|   |   |---- MonoMod.RuntimeDetour.dll (86.50KB)
|   |   |---- MonoMod.RuntimeDetour.xml (8.43KB)
|   |   |---- MonoMod.Utils.dll (173.50KB)
|   |   `---- MonoMod.Utils.xml (76.47KB)
|   |---+ patchers
|   |   |---+ QModManager
|   |   |   |---- AssetsTools.NET.dll (148.00KB)
|   |   |   |---- cldb.dat (325.90KB)
|   |   |   |---- QModManager.exe (119.50KB)
|   |   |   |---- QModManager.QModPluginGenerator.dll (19.00KB)
|   |   |   |---- QModManager.UnityAudioFixer.dll (8.50KB)
|   |   |   `---- QModManager.UnityAudioFixer.xml (2.41KB)
|   |   `---- MirrorInternalLogs.dll (19.50KB)
|   |---+ plugins
|   |   |---+ QModManager
|   |   |   |---- QModInstaller.dll (83.00KB)
|   |   |   |---- QModInstaller.xml (27.70KB)
|   |   |   |---- QModManager.QMMLoader.dll (6.00KB)
|   |   |   `---- QModManager.QMMLoader.xml (503.00B)
|   `---- LogOutput.log (4.00KB)
|---+ MonoBleedingEdge
|   `---- (Folder content not shown)
|---+ OST
|   `---- (Folder content not shown)
|---+ QMods
|---+ SNAppData
|   `---- (Folder content not shown)
|---+ steam_shader_cache
|   `---- (Folder content not shown)
|---+ Subnautica_Data
|   `---- (Folder content not shown)
|---- doorstop_config.ini (361.00B)
|---- qmodmanager_log-Subnautica.txt (5.23KB)
|---- QMods.7z (9.55MB)
|---- steam_api64.dll (201.91KB)
|---- Subnautica.exe (636.50KB)
|---- Subnautica32.exe (68.50KB)
|---- unins000.dat (33.80KB)
|---- unins000.exe (2.54MB)
|---- UnityCrashHandler64.exe (1.04MB)
|---- UnityPlayer.dll (24.69MB)
|---- winhttp.dll (20.00KB)
[QModManager:INFO] Folder structure ended.
[QModManager:ERROR] There was an error while trying to apply Harmony patches.
[QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 0100001d (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Utility.Logger.Debug (System.String msg) [0x00000] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at QModManager.Patching.Patcher.PatchHarmony () [0x00000] in <e5201b7381ab455e9d160b6c7334eb46>:0
[QModManager:FATAL] An unhandled exception has been caught! Patching ended prematurely!
[QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 0100001d (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Checks.VersionCheck.Check () [0x00000] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at QModManager.Patching.Patcher.Patch () [0x00123] in <e5201b7381ab455e9d160b6c7334eb46>:0
ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000d] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at QModManager.QMMLoader.InitializeQMods () [0x00000] in <df47f8090f2a4926a95883061a037879>:0 
  at QModManager.QMMLoader.InitializeQModManager () [0x00005] in <df47f8090f2a4926a95883061a037879>:0 
  at (wrapper dynamic-method) PlatformUtils.DMD<PlatformUtils::PlatformInitAsync>(PlatformUtils)
  at PlatformUtils.Awake () [0x00047] in <57e8189cd712490d99edb423024ae4d1>:0 
UnityEngine.Object:Internal_InstantiateSingle_Injected(Object, Vector3&, Quaternion&)
UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
SystemsSpawner:Awake()
 
(Filename: <351e49e2a5bf4fd6beabb458ce2255f3> Line: 0)
OnQuit behaviour queued for deferred registering, platform services aren't initialized. 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)
Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 3682.
Total: 20.448400 ms (FindLiveObjects: 0.339300 ms CreateObjectMapping: 0.154000 ms MarkObjects: 19.937500 ms  DeleteObjects: 0.017400 ms)
OnQuit behaviour queued for deferred registering, platform services aren't initialized. 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Material doesn't have a texture property '_MainTex' 
(Filename:  Line: 1452)
Material doesn't have a texture property '_MainTex' 
(Filename:  Line: 1452)
AddressablesUtility.LoadSceneAsync loading scene: MenuEnvironment in mode Additive 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 0100001d (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Utility.Logger.Debug (System.String msg, System.Boolean showOnScreen, System.String callingAssembly, System.Boolean force) [0x00003] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at QModManager.Utility.Logger.Debug (System.String msg) [0x00000] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at QModManager.Utility.Dialog+Button+<>c.<.cctor>b__8_0 () [0x00045] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at QModManager.Utility.Dialog+<>c__DisplayClass11_0.<ShowDialogEnumerator>b__0 (System.Boolean leftButtonClicked) [0x00017] in <e5201b7381ab455e9d160b6c7334eb46>:0 
  at uGUI_SceneConfirmation.Close (System.Boolean result) [0x0001b] in <57e8189cd712490d99edb423024ae4d1>:0 
  at uGUI_SceneConfirmation.OnYes () [0x00000] in <57e8189cd712490d99edb423024ae4d1>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00010] in <e80855beea5a4202b716487decbeb6fb>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00022] in <e80855beea5a4202b716487decbeb6fb>:0 
  at UnityEngine.UI.Button.Press () [0x0001c] in <a93a5d8ea4b7447a9e03407fddf6d8a3>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00009] in <a93a5d8ea4b7447a9e03407fddf6d8a3>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <a93a5d8ea4b7447a9e03407fddf6d8a3>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00063] in <a93a5d8ea4b7447a9e03407fddf6d8a3>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
FPSInputModule:ProcessMousePress(MouseButtonEventData)
FPSInputModule:ProcessMouseEvent()
FPSInputModule:OnUpdate()
ManagedUpdate:Execute(Queue)
ManagedUpdate:LateUpdate()
 
(Filename: <e5201b7381ab455e9d160b6c7334eb46> Line: 0)
NullReferenceException: Object reference not set to an instance of an object
  at PlatformUtils.GetCurrentUserId () [0x00000] in <57e8189cd712490d99edb423024ae4d1>:0 
  at uGUI_FeedbackCollector.GetPlayerOnlineId () [0x00016] in <57e8189cd712490d99edb423024ae4d1>:0 
  at uGUI_FeedbackCollector+<RepliesRoutine>d__63.MoveNext () [0x00076] in <57e8189cd712490d99edb423024ae4d1>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <e80855beea5a4202b716487decbeb6fb>:0 
 
(Filename: <57e8189cd712490d99edb423024ae4d1> Line: 0)
Setting up 4 worker threads for Enlighten.
Thread -> id: 3890 -> priority: 1
Thread -> id: 25a0 -> priority: 1
Thread -> id: 1cd0 -> priority: 1

**Comment by PrimeSonic** [comment]
`[QModManager:INFO] Game Version: 67522`
You're on the Experimental branch. This is _not_ supported by QModManager (and most mods).
