### ISSUE TITLE
4.0.4. Subnautica BZ Mods not loading anymore

### ISSUE THREAD

**Issue by spyro2000** [SubnauticaModding/QModManager#215]
**Describe the bug**
I can't get any mod to load after the Seathworthy update. Did a full reinstall of the game. I am not on the experimental branch. I redownloaded all mods und re-installed QMod Manager 4.0.4 many times. Also tried 4.0.23. The mods just don't load. :(

**Screenshots**

Install dir:

![image](https://user-images.githubusercontent.com/8479925/110843292-64ab5a00-82a8-11eb-9341-5a6d20a13a2c.png)

**Additional info**

Here's the full log:

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/Mono/data-0000015F93DF0080.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/Mono/data-0000015F93E96890.dll
Initialize engine version: 2019.4.9f1 (630)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version:  Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
Vendor:
VRAM:     8088 MB
Driver:   27.21.14.5671
Begin MonoManager ReloadAssembly
- Completed reload, in  0.055 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed 
(Filename:  Line: 369)
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.

[Message:   BepInEx] BepInEx 5.4.5.0 - SubnauticaZero
[Info   :   BepInEx] Running under Unity v2019.4.9.630
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.OculusNewtonsoftRedirect 4.0.4.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.0.4.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.0.4.0]
[Info   :   BepInEx] 5 patcher plugins loaded
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Newtonsoft.Json] with [QModManager.OculusNewtonsoftRedirect]
[Info   :QModPluginGenerator] Loading QMMAssemblyCache...
[Info   :QModPluginGenerator] QMMAssemblyCache loaded in 30 ms.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Warning:   BepInEx] Shimming C:\Program Files (x86)\Steam\steamapps\common\SubnauticaZero\QMods\UnSlowSeaTruck\UnSlowSeaTruck.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/Mono/data-000001601F8CF850.dll
[Warning:   BepInEx] Shimming C:\Program Files (x86)\Steam\steamapps\common\SubnauticaZero\QMods\SubnauticaMap_BZ\SubnauticaMap_BZ.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/Mono/data-000001601FA69010.dll
[Warning:   BepInEx] Shimming C:\Program Files (x86)\Steam\steamapps\common\SubnauticaZero\QMods\EasyCraft_BZ\EasyCraft_BZ.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/SubnauticaZero/SubnauticaZero_Data/Mono/data-000001601F8D1E60.dll
[Info   :   BepInEx] 5 plugins to load
[Info   :   BepInEx] Loading [QMMLoader 1.0.1]
[Info   :   BepInEx] Loading [EasyCraft 1.1.2.0]
[Info   :   BepInEx] Loading [Quick Slots 1.5.0.0]
[Info   :   BepInEx] Loading [SubnauticaMap 1.1.9.0]
[Info   :   BepInEx] Loading [UnSlowSeaTruck 1.2.1.0]
[Message:   BepInEx] Chainloader startup complete
UnloadTime: 1.114100 ms
AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Unloading 4 Unused Serialized files (Serialized files now loaded: 9)
UnloadTime: 1.045700 ms
Initializing Steam services 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Missing Steam DRM 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Couldn't initialize Steamworks 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
AutomatedProfiler CommandLineArguments: C:\Program Files (x86)\Steam\steamapps\common\SubnauticaZero\SubnauticaZero.exe 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)
Unloading 10 unused Assets to reduce memory usage. Loaded Objects now: 4825.
Total: 23.327000 ms (FindLiveObjects: 0.312300 ms CreateObjectMapping: 0.057200 ms MarkObjects: 22.916600 ms  DeleteObjects: 0.040300 ms)
Setting up 8 worker threads for Enlighten.
Thread -> id: d18 -> priority: 1
Thread -> id: 4f90 -> priority: 1
Thread -> id: 545c -> priority: 1
Thread -> id: 1be4 -> priority: 1
Thread -> id: 683c -> priority: 1
Thread -> id: 1364 -> priority: 1

**Comment by desperationfighter** [comment]
Hi,
please don't open a Bug Report until you know i is a Bug.
As for now i believe thats only a issue.
I see you don't start the Game over the Steam Launcher. That already can be a Issue.

Please visit: https://discord.gg/UpWuWwq
and provide the log in the "help-and-support" Channel where you started the game via Steam launcher.
Also just drag and drop the qmod Log File to the chat. Don't copy the Text of it to the chat. It is easier to read.

**Comment by MrPurple6411** [comment]
> Initializing Steam services
> (Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> Missing Steam DRM
> (Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> Couldn't initialize Steamworks

When you see these lines in the log file it means steam itself is either not running or has not loaded the game correctly. 

restart steam and then load the game again.

**Comment by spyro2000** [comment]
Ok, thank you. Will do!
