### ISSUE TITLE
Qmod problem touch ingame

### ISSUE THREAD

**Issue by dexter74** [SubnauticaModding/QModManager#217]
**Describe the bug**

Following the installation of the latest release of Qmod, after launching a new game, the keys of the game does not work. Can't make echap

**Screenshots**

NONE 

**Additional info**

Fev 2021 - Build Game 42690
QMod 4.0.2.3

**Comment by desperationfighter** [comment]
If i see correct you are talking about Below Zero as the Build is 42xxx.
And QMod 4.0.2.3 is NOT the latest Version for Below Zero. So this is not a Bug.
Please check if you installed the correct AND latest Version.

If you continue to have Problems please visit the Subnautica Modding Discord:  https://discord.gg/UpWuWwq

**Comment by dexter74** [comment]
On github the last version:  QMod 4.0.2.3 

https://github.com/SubnauticaModding/QModManager/releases

**Comment by desperationfighter** [comment]
Github is for Code Controll and NOT the Official Supportet Share Channel.
Also your are Looking for the Version that is for the Base Game there is a seperated Version for BelowZero

Please visit the Nexus Site for Official Downloads.
https://www.nexusmods.com/subnauticabelowzero/mods/1?tab=files
