### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by nahueltech** [SubnauticaModding/QModManager#220]
It wont let me play :( here is the problem: 
[Message:   BepInEx] BepInEx 5.4.5.0 - Subnautica
[Info   :   BepInEx] Running under Unity v2019.4.9.630
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.0.2.6]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.0.2.6]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Fatal  :QModPluginGenerator] An exception occurred while attempting to generate BepInEx PluginInfos: Could not resolve type with token 01000025 (from typeref, class/assembly Oculus.Newtonsoft.Json.Bson.BsonReader, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null).
[Fatal  :QModPluginGenerator] Beginning stacktrace:
[Fatal  :QModPluginGenerator]   at QModManager.QModPluginGenerator.GetPluginCache () [0x00000] in <773766e20f9a4863a8c37f9f0e678d84>:0 
  at QModManager.QModPluginGenerator.Finish () [0x00000] in <773766e20f9a4863a8c37f9f0e678d84>:0 
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [QMMLoader 1.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] [QModManager:INFO] Detected game: Subnautica
[Info   :   Console] [QModManager:INFO] Game Version: 67737 Build Date: 01-enero-0001
[Info   :   Console] [QModManager:INFO] Loading QModManager v4.0.2.6...
[Info   :   Console] [QModManager:INFO] Today is 25-abril-2021
[Info   :   Console] [QModManager:INFO] Folder structure:
[Info   :   Console] + Subnautica v67737
[Info   :   Console] |---+ BepInEx
[Info   :   Console] |   |---+ cache
[Info   :   Console] |   |   |---- chainloader_typeloader.dat (320.00B)
[Info   :   Console] |   |   `---- harmony_interop_cache.dat (627.00B)
[Info   :   Console] |   |---+ config
[Info   :   Console] |   |   |---- BepInEx.cfg (4.88KB)
[Info   :   Console] |   |   `---- MirrorInternalLogs.cfg (788.00B)
[Info   :   Console] |   |---+ core
[Info   :   Console] |   |   |---- 0Harmony.dll (174.00KB)
[Info   :   Console] |   |   |---- 0Harmony.xml (240.57KB)
[Info   :   Console] |   |   |---- 0Harmony109.dll (42.00KB)
[Info   :   Console] |   |   |---- 0Harmony12.dll (66.00KB)
[Info   :   Console] |   |   |---- 0Harmony20.dll (109.00KB)
[Info   :   Console] |   |   |---- BepInEx.dll (108.50KB)
[Info   :   Console] |   |   |---- BepInEx.Harmony.dll (5.50KB)
[Info   :   Console] |   |   |---- BepInEx.Harmony.xml (3.96KB)
[Info   :   Console] |   |   |---- BepInEx.Preloader.dll (40.50KB)
[Info   :   Console] |   |   |---- BepInEx.Preloader.xml (7.52KB)
[Info   :   Console] |   |   |---- BepInEx.xml (82.72KB)
[Info   :   Console] |   |   |---- HarmonyXInterop.dll (23.00KB)
[Info   :   Console] |   |   |---- Mono.Cecil.dll (331.50KB)
[Info   :   Console] |   |   |---- Mono.Cecil.Mdb.dll (42.00KB)
[Info   :   Console] |   |   |---- Mono.Cecil.Pdb.dll (84.50KB)
[Info   :   Console] |   |   |---- Mono.Cecil.Rocks.dll (27.00KB)
[Info   :   Console] |   |   |---- MonoMod.RuntimeDetour.dll (86.50KB)
[Info   :   Console] |   |   |---- MonoMod.RuntimeDetour.xml (8.43KB)
[Info   :   Console] |   |   |---- MonoMod.Utils.dll (173.50KB)
[Info   :   Console] |   |   `---- MonoMod.Utils.xml (76.47KB)
[Info   :   Console] |   |---+ patchers
[Info   :   Console] |   |   |---+ QModManager
[Info   :   Console] |   |   |   |---- AssetsTools.NET.dll (148.00KB)
[Info   :   Console] |   |   |   |---- cldb.dat (325.90KB)
[Info   :   Console] |   |   |   |---- QModManager.exe (119.50KB)
[Info   :   Console] |   |   |   |---- QModManager.QModPluginGenerator.dll (19.00KB)
[Info   :   Console] |   |   |   |---- QModManager.UnityAudioFixer.dll (8.50KB)
[Info   :   Console] |   |   |   `---- QModManager.UnityAudioFixer.xml (2.41KB)
[Info   :   Console] |   |   `---- MirrorInternalLogs.dll (19.50KB)
[Info   :   Console] |   |---+ plugins
[Info   :   Console] |   |   |---+ QModManager
[Info   :   Console] |   |   |   |---- QModInstaller.dll (83.00KB)
[Info   :   Console] |   |   |   |---- QModInstaller.xml (27.70KB)
[Info   :   Console] |   |   |   |---- QModManager.QMMLoader.dll (6.00KB)
[Info   :   Console] |   |   |   `---- QModManager.QMMLoader.xml (503.00B)
[Info   :   Console] |   `---- LogOutput.log (4.00KB)
[Info   :   Console] |---+ MonoBleedingEdge
[Info   :   Console] |   `---- (Folder content not shown)
[Info   :   Console] |---+ OST
[Info   :   Console] |   `---- (Folder content not shown)
[Info   :   Console] |---+ QMods
[Info   :   Console] |---+ SNAppData
[Info   :   Console] |   `---- (Folder content not shown)
[Info   :   Console] |---+ Subnautica_Data
[Info   :   Console] |   `---- (Folder content not shown)
[Info   :   Console] |---- doorstop_config.ini (361.00B)
[Info   :   Console] |---- qmodmanager_log-Subnautica.txt (5.33KB)
[Info   :   Console] |---- steam_api64.cdx (201.91KB)
[Info   :   Console] |---- steam_api64.dll (292.78KB)
[Info   :   Console] |---- steam_emu.ini (2.44KB)
[Info   :   Console] |---- Subnautica.exe (636.50KB)
[Info   :   Console] |---- Subnautica32.exe (68.50KB)
[Info   :   Console] |---- UnityCrashHandler64.exe (1.04MB)
[Info   :   Console] |---- UnityPlayer.dll (24.69MB)
[Info   :   Console] |---- winhttp.dll (20.00KB)
[Info   :   Console] [QModManager:INFO] Folder structure ended.
[Info   :   Console] [QModManager:WARN] Ahoy, matey! Ye be a pirate!
[Info   :   Console] [QModManager:ERROR] There was an error while trying to apply Harmony patches.
[Info   :   Console] [QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 0100001d (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Utility.Logger.Debug (System.String msg) [0x00000] in <d9dbdb2cb1ad4a42a933d61fd2134a09>:0 
  at QModManager.Patching.Patcher.PatchHarmony () [0x00000] in <d9dbdb2cb1ad4a42a933d61fd2134a09>:0 
[Info   :   Console] [QModManager:FATAL] An unhandled exception has been caught! Patching ended prematurely!
[Info   :   Console] [QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 0100001d (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Checks.VersionCheck.Check () [0x00000] in <d9dbdb2cb1ad4a42a933d61fd2134a09>:0 
  at QModManager.Patching.Patcher.Patch () [0x00123] in <d9dbdb2cb1ad4a42a933d61fd2134a09>:0

**Comment by Mavoc** [comment]
Things like this can happen when you pirate a game.  Perhaps you should get a legitimate copy and try again with that.
