### ISSUE TITLE
Subnautica - below zero - QMod-manager

### ISSUE THREAD

**Issue by TheYeGh** [SubnauticaModding/QModManager#224]
installing the mod causes alerts of antivirus programs, and even complete removal of QMOD without the possibility of installing it
occurs with Panda Software and Windows Deffender - regardless of installed updates

**Comment by desperationfighter** [comment]
as long you have it from Nexusmods is a false positive.
Thats sometime happen to people sometimes.
the best you can do is making a antivir exlusion for the BepInEx Folder or the complete Subnautica Folder.
