### ISSUE TITLE
Non-compliant zip download

### ISSUE THREAD

**Issue by rhoot** [SubnauticaModding/QModManager#225]
The zip file provided for the manual install of 4.1.2 on Nexus Mods doesn't follow the zip standard and as such can't be used with all zip applications. In particular, the file can't be properly extracted on Linux (I tried both GNOME Archive Manager and command line `unzip`). Instead I ended up having to use a Windows VM to properly extract it.

The problem is the paths inside the zip file contain backslashes. Per the zip standard:

> 4.4.17.1 The name of the file, with optional relative path. The path stored MUST NOT contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes `/` as opposed to backwards slashes `\` for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

It appears some zip tools in Windows fails to follow this due to an earlier [bug in .NET Framework's zip implementation](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator).

I don't know what tool was used to create that zip file, but:
- The 4.0.2.6 download for Subnautica did not have that problem.
- The 4.0.3.4 download for Below Zero also did not have that problem.
- The 4.1.2 download for Below Zero does.

If you could switch back to an archiver that produces proper zip files for future versions, it would save myself (and probably like 2 other people) a lot of trouble. 😄

**Comment by MrPurple6411** [comment]
I recently automated the zip file creation directly in the build process to make our lives easier to build it and get updates out as easily as possible...  Going back to manual would be quite irritating but I will look to see if there is an alternative I can use to the PowerShell compress system I just setup.  no promises
