### ISSUE TITLE
Subnautica (build 67855)

### ISSUE THREAD

**Issue by alphabrain** [SubnauticaModding/QModManager#228]
Game loads normally, buy QMod doesn't work at all.
[qmodmanager_log-Subnautica.txt](https://github.com/SubnauticaModding/QModManager/files/6509434/qmodmanager_log-Subnautica.txt)

**Comment by Metious** [comment]
Github issues are _not_ used to provide support for people here. please join the [Subnautica Modding Discord Server](https://discord.gg/UpWuWwq).
