### ISSUE TITLE
How would I install qModManager on MacOS?

### ISSUE THREAD

**Issue by AstroOrbis** [SubnauticaModding/QModManager#229]
BTW it's installed using Steam if that helps :3

**Comment by PrimeSonic** [comment]
We do not have anyone currently on the team with the hardware and knowhow needed to support QModManager on Mac.

Until then, we cannot provide support for Mac installations.

**Comment by AstroOrbis** [comment]
If need be I can help :)

**Comment by PrimeSonic** [comment]
If you're willing and able to help out, you should join the modding community on the [Subnautica Modding Discord](https://discord.gg/UpWuWwq).

If you want to help with making QModManager work on Mac, you would ideally already know about modding with Harmony (and BepInEx).

**Comment by tobiasstrebitzer** [comment]
@AstroOrbis have a look at #201 and https://github.com/tobiasstrebitzer/QModManager/blob/osx/MacOSX/README.md

**Comment by AstroOrbis** [comment]
I’ll check it out once I get back on my computer!
