### ISSUE TITLE
Add Version Compatability Information

### ISSUE THREAD

**Issue by martilidad** [SubnauticaModding/QModManager#231]
**Describe the issue**
I installed the latest Version of QModmanager and it refuses to work with my Below Zero Version. 
It would be nice of you to **document the last tested working Game Version the Manager works with.**
I get this log when using the latest (4.1.3) installer. I tried both normal and experimental. I understand that updates will break the Mod Manager from time to time and I'm very grateful for your work. Keep it up ;)

> [QModManager:INFO] Detected game: BelowZero
> [QModManager:INFO] Game Version: 44290 Build Date: 11-Mai-2021
> [QModManager:INFO] Loading QModManager v4.1.3 built for BelowZero v44291...
> [QModManager:INFO] Today is 26-Mai-2021_18:10:07
> [QModManager:FATAL] A fatal error has occurred. An invalid game version was detected!
> [QModManager:FATAL] A fatal patching exception has been caught! Patching ended prematurely!
> [QModManager:ERROR] QModManager.Patching.FatalPatchingException: An invalid game version was detected!

**Additional info**
I removed all Files from the QMods folder. I am using the (not so) Epic Games Store version.

**Comment by martilidad** [comment]
Sorry I was unclear in my original post. I have game Version 44290-xxx and had to go through all the trouble of trying different versions of the Mod Manager to figure out which works. It would be nice if the information was available on all download platforms.

**Comment by tobeyStraitjacket** [comment]
So, it looks like you are running the version built for the `experimental` branch of BZ instead of the one for the standard branch. You can tell them apart because of the `.EXP` suffix in the download in the releases page here in GitHub. The one suffixed `.STABLE` is always for the standard branch.

**Comment by tobeyStraitjacket** [comment]
Also, if for whatever reason you need to know which version each of the builds was built for, you can see them all in one place here, but on Epic, you always want the `.STABLE` suffix, as the epic store doesn't (AFAIK?) allow you to switch branches:

https://github.com/SubnauticaModding/QModManager/blob/Dev/QModManager/Patching/GameDetector.cs#L19-L30
```cs
        private static readonly Dictionary<QModGame, int> SupportedGameVersions = new Dictionary<QModGame, int>
        {
#if SUBNAUTICA_STABLE
            { QModGame.Subnautica, 65786 }
#elif BELOWZERO_STABLE
            { QModGame.BelowZero, 44290 }
#elif SUBNAUTICA_EXP
            { QModGame.Subnautica, 67843 }
#elif BELOWZERO_EXP
            { QModGame.BelowZero, 44291 }
#endif
        };
```

**Comment by martilidad** [comment]
Yeah, sorry to have bothered you with this. I kinda jumped the gun. There was a completely different error with the normal exe. For some reason using the Qmod Sam manager to start the game fixed those errors. ¯\_(ツ)_/¯
