### ISSUE TITLE
Nexus Mod Manager Auto Install, "Could Not Find Managed Directory"

### ISSUE THREAD

**Issue by ScaryNed** [SubnauticaModding/QModManager#233]
**Problem Description**

After Installation, Subnautica does not seem to activate or recognize any mods rely on QMod. Opening/Activating the Qmod application located below tells me that the application couldn't find the managed directory, despite using the auto install feature available on Nexus Mods.

**Screenshots**

File location after Nexus Mod Auto Installation:
![Capture](https://user-images.githubusercontent.com/32000514/119867762-3f63da80-beec-11eb-81ca-4387e043ccba.PNG)
Result of activating:
![Capture 2](https://user-images.githubusercontent.com/32000514/119867767-412d9e00-beec-11eb-895c-77b2729a9ec8.PNG)

**Additional info**

I'm certain that it's an issue on placement for the files, but I'm not sure what the appropriate location for the unzipped package is. I've looked up tutorials to see if their placement is similar to my own, but none of the ones I've found showed me end result of where all the files should look like when successfully downloaded. Let me know what steps I need to take to trouble shoot this (Didn't see any on the Nexus QMod Page

**Comment by PrimeSonic** [comment]
You are not supposed to manually run that application.
Once installed, you simply run the game and the mod loader does its thing.

If you need assistance or are running into technical problems, the Github Issues page is the wrong place for it. 
The people on the Subnautica Modding Discord will be able to help. 
https://discord.gg/UpWuWwq

**Comment by ScaryNed** [comment]
> You are not supposed to manually run that application.
> Once installed, you simply run the game and the mod loader does its thing.
> 
> If you need assistance or are running into technical problems, the Github Issues page is the wrong place for it.
> The people on the Subnautica Modding Discord will be able to help.
> https://discord.gg/UpWuWwq

Thanks for the reply, will ask there. Have a good day!
