### ISSUE TITLE
Mac Cannot open assembly 'QModManager.exe': File does not contain a valid CIL image

### ISSUE THREAD

**Issue by ParRaDoxChamp** [SubnauticaModding/QModManager#246]
**Describe the issue**
 when I run Mono QModManager.exe it says the file does not contain a valid CIL image. I believe that it's because we have to mcs the .cs first if yall can make a .cs file because we have to compile the .cs file first then run mono QModManager.exe

**Screenshots**

**Additional info**
 This is where I found why it's giving us that error. "https://superuser.com/questions/489328/file-does-not-contain-a-valid-cil-image"

**Comment by tobeyStraitjacket** [comment]
What are you doing exactly? The file is already compiled. You don't need to run QModManager.exe anyway.

**Comment by tobeyStraitjacket** [comment]
If you're trying to follow some tutorial on how to run QMM on mac, can you please link it? Because the steps you are doing seem bizarre.

**Comment by tobeyStraitjacket** [comment]
What steps have you taken prior to this? Did you download the Vortex .zip install or the .exe install? I assume the .zip? If so, please try following these instructions:

- Extract the contents of the QModManager .zip build into the game root folder
- Go to https://github.com/BepInEx/BepInEx/releases and download the latest `Unix` build of BepInEx, extract it into the game root folder, override when asked
- Configure the `run_bepinex.sh` file as needed
- Try running the game via the `run_bepinex.sh` script

https://docs.bepinex.dev/v5.0/articles/user_guide/installation.html#where-to-download-bepinex

**Comment by tobeyStraitjacket** [comment]
Also, if the game installed via Steam, you'll need to see the following:
https://docs.bepinex.dev/v5.4.4/articles/advanced/steam_interop.html?tabs=tabid-1

**Comment by ParRaDoxChamp** [comment]
I was doing this (https://github.com/SubnauticaModding/QModManager/pull/34/files/f4f7e225137c94f321ca8e70b5ee22fd9298bebd#diff-2e099e42d368d2679e3b8f4a9f7016cd832caecc00ea2306eba1b08060d2105b) to download QMM but my terminal was giving me Cannot open assembly 'QModManager.exe': File does not contain a valid CIL image when I run mono QModManager.exe

**Comment by tobeyStraitjacket** [comment]
> I was doing this (https://github.com/SubnauticaModding/QModManager/pull/34/files/f4f7e225137c94f321ca8e70b5ee22fd9298bebd#diff-2e099e42d368d2679e3b8f4a9f7016cd832caecc00ea2306eba1b08060d2105b)

There's a reason none of that is in the repo anymore. It's long-outdated information.

**Comment by ParRaDoxChamp** [comment]
oh ok

**Comment by tobeyStraitjacket** [comment]
> oh ok

Try following the instructions I gave you and see if you have any luck. We currently don't have anyone on the QMM team with a Mac, so we can't test how well QMM works on Mac.

**Comment by tobeyStraitjacket** [comment]
There's also these instructions, again, I'm not sure if they work, because I can't test any of it:
https://github.com/SubnauticaModding/QModManager/issues/201#issuecomment-845533923
