### ISSUE TITLE
Subnautica v68222

### ISSUE THREAD

**Issue by valador** [SubnauticaModding/QModManager#254]
**Describe the bug**
qmodmanager not work with Subnautica build v68222

**Additional info**
I install Subnautica build v68222 with my mod pack and... fail. Please fix this.
Game start but no mods effect in game.

[Log](https://pastebin.com/Q37kaMrK)

**Comment by PrimeSonic** [comment]
Delete files in your Subnautica_Data/Managed folder and re-download them.

This is an issue with your files.
This is not a bug. 

Please do not use the Issues section for anything that could be resolved on the Discord server. 
The Github repo is not the place for troubleshooting and tech support.

**Comment by Metious** [comment]
Pirated copies are not supported by us, you're on your own.
