### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by JamesTheMaker** [SubnauticaModding/QModManager#257]
**Describe the problem**
When I attempt to run the .exe, it sends the error "Runtime error" with the info of "SWbemObjectSet: Invalid class"

**Screenshots**
![qmodmanager](https://user-images.githubusercontent.com/79481373/141688681-46a2ee32-dc1c-4bea-83fb-de9761a9e102.PNG)

**Additional info**
I've already uninstalled Nitrox, so I know that can't be the problem

**Comment by desperationfighter** [comment]
Normally you can just press ok and continue. Its a known error for a long time now but it does not create any error in the end.
Alternative you can simply use the Zip File Version and place everything yourself instead using the installer.
If you have any continues questions a good place to visit is the Modding Discord https://discord.gg/UpWuWwq .
