### ISSUE TITLE
QMOD Manager not working 

### ISSUE THREAD

**Issue by Dodo303x** [SubnauticaModding/QModManager#258]
I installed QMod Manager with the .exe and if didn´t work i also tried installing with the .zip file but nothing seemed to work properly. I can start up Subnautica normally but if I go into options there isn´t any Mods Section and the Mods aren´t working. 
There aren´t any error messages and/or bugs with the normal subnautica game.

![image](https://user-images.githubusercontent.com/94912685/143036608-82544507-6a23-4ba3-af2a-a1148c43b5f2.png)
![image](https://user-images.githubusercontent.com/94912685/143036891-1d84572c-5b24-4f83-bb9a-1be06430f716.png)

**Comment by Metious** [comment]
Hello there, this looks like an antivirus of yours is blocking QModManager from running. With whatever Antivirus you're using, make an exclusion for your Subnautica folder, then restart your pc and relaunch the game. if that didn't solve it, please visit the Subnautica Modding discord server: https://discord.gg/UpWuWwq.
