### ISSUE TITLE
Mod menu not showing

### ISSUE THREAD

**Issue by Muffins-the-Cat** [SubnauticaModding/QModManager#259]
Whenever I boot up the game, the mod menus don't show up. For mods such as resource monitor, the resource monitor doesn't show up in the habitat builder menu but some parts of other mods work. Some features of the Tweaks and Fixes mod work but nothing else does.

I have tried completely uninstalling and reinstalling multiple different versions of the mod manager, unmanaging and remanaging the game in Vortex (qmod was installed manually with the EXE file), and looking all over the internet for answers. I will only uninstall and reinstall the game if it is a complete last resort as I have crappy wifi.

**Comment by desperationfighter** [comment]
i don't thing thats a real bug.
Resource Monitor is also not updated for ages and pretty buggy. I not recommen you to use it anyway.

However the best you can do is: https://discord.gg/UpWuWwq join the Modding Discord and visit the Help and Support Channel
