### ISSUE TITLE
I cant save or install mods

### ISSUE THREAD

**Issue by MagicJungle7053** [SubnauticaModding/QModManager#263]
After I installed Qmodmanager it doesn't let me create save games nor let me use mods
Here is the log:

Fallback handler could not load library C:/Users/Riley/Desktop/DUMP/Subnautica_Data/Mono/data-0000027016F3B040.dll
Initialize engine version: 2019.4.9f1 (636)
[Subsystems] Discovering subsystems at path C:/Users/Riley/Desktop/DUMP/Subnautica_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version:  Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f99)
Vendor:
VRAM:     3962 MB
Driver:   30.0.14.9729
Begin MonoManager ReloadAssembly
- Completed reload, in  0.073 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed 
(Filename:  Line: 369)
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"! 
(Filename:  Line: 1889)
UnloadTime: 0.595700 ms
AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Unloading 4 Unused Serialized files (Serialized files now loaded: 9)
UnloadTime: 1.925200 ms

[Message:   BepInEx] BepInEx 5.4.15.0 - Subnautica (06/01/2022 18:22:14)
[Info   :   BepInEx] Running under Unity v2019.4.9.636
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.15.0]
[Warning:   BepInEx] Shimming C:\Users\Riley\Desktop\DUMP\BepInEx\patchers\BepInEx.MultiFolderLoader.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MultiFolderLoader 1.3.1.0]
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.3.0.0]
[Info   :   BepInEx] 5 patcher plugins loaded
[Info   :MultiFolderLoader] Loading preloader patchers from mod
[Info   :MultiFolderLoader] Loading 0 preloader patchers from mods...
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [Assembly-CSharp] with [BepInEx.Chainloader]
[Fatal  :QModPluginGenerator] An exception occurred while attempting to generate BepInEx PluginInfos: Could not resolve type with token 01000026 (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonTextReader, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null).
[Fatal  :QModPluginGenerator] Beginning stacktrace:
[Fatal  :QModPluginGenerator]   at QModManager.QModPluginGenerator.GetPluginCache () [0x00000] in <3064c81e2543464ab3b761446af64c51>:0 
  at QModManager.QModPluginGenerator.Finish () [0x00000] in <3064c81e2543464ab3b761446af64c51>:0
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :MultiFolderLoader] Finding plugins from mods...
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [QModManager.LogFilter 4.3.0]
[Info   :   BepInEx] Loading [QMMLoader 4.3.0]
[QModManager:INFO] Detected game: Subnautica
[QModManager:INFO] Game Version: 68020 Build Date: 01-January-0001
[QModManager:INFO] Loading QModManager v4.3 built for Subnautica v65786...
[QModManager:INFO] Today is 06-January-2022_18:36:28
[QModManager:INFO] Game Folder structure:
+ DUMP
|---+ BepInEx
|   |---+ cache
|   |   |---- chainloader_typeloader.dat (352.00B)
|   |   `---- harmony_interop_cache.dat (925.00B)
|   |---+ config
|   |   |---- BepInEx.cfg (5.43KB)
|   |   `---- MirrorInternalLogs.cfg (785.00B)
|   |---+ core
|   |   |---- 0Harmony.dll (184.50KB)
|   |   |---- 0Harmony.xml (251.13KB)
|   |   |---- 0Harmony109.dll (42.00KB)
|   |   |---- 0Harmony12.dll (66.00KB)
|   |   |---- 0Harmony20.dll (109.00KB)
|   |   |---- BepInEx.dll (112.50KB)
|   |   |---- BepInEx.Harmony.dll (5.50KB)
|   |   |---- BepInEx.Harmony.xml (3.96KB)
|   |   |---- BepInEx.Preloader.dll (41.00KB)
|   |   |---- BepInEx.Preloader.xml (7.79KB)
|   |   |---- BepInEx.xml (83.72KB)
|   |   |---- HarmonyXInterop.dll (23.00KB)
|   |   |---- Mono.Cecil.dll (331.50KB)
|   |   |---- Mono.Cecil.Mdb.dll (42.00KB)
|   |   |---- Mono.Cecil.Pdb.dll (84.50KB)
|   |   |---- Mono.Cecil.Rocks.dll (27.00KB)
|   |   |---- MonoMod.RuntimeDetour.dll (102.00KB)
|   |   |---- MonoMod.RuntimeDetour.xml (9.19KB)
|   |   |---- MonoMod.Utils.dll (182.00KB)
|   |   `---- MonoMod.Utils.xml (76.95KB)
|   |---+ patchers
|   |   |---+ QModManager
|   |   |   |---- AssetsTools.NET.dll (170.50KB)
|   |   |   |---- cldb.dat (325.90KB)
|   |   |   |---- QModManager.exe (119.50KB)
|   |   |   |---- QModManager.QModPluginGenerator.dll (18.00KB)
|   |   |   |---- QModManager.UnityAudioFixer.dll (8.00KB)
|   |   |   `---- QModManager.UnityAudioFixer.xml (2.41KB)
|   |   |---- BepInEx.MultiFolderLoader.dll (14.50KB)
|   |   `---- MirrorInternalLogs.dll (19.50KB)
|   |---+ plugins
|   |   |---+ QModManager
|   |   |   |---- QModInstaller.dll (86.50KB)
|   |   |   `---- QModInstaller.xml (29.31KB)
|   `---- LogOutput.log (4.00KB)
|---+ BepInEx_Shim_Backup
|   |---+ BepInEx
|   |   |---+ patchers
|   |   |   `---- BepInEx.MultiFolderLoader.dll (14.50KB)
|---+ MonoBleedingEdge
|   `---- (Folder content not shown)
|---+ OST
|   `---- (Folder content not shown)
|---+ QMods
|---+ Subnautica_Data
|   `---- (Folder content not shown)
|---- appxmanifest.xml (2.33KB)
|---- doorstop_config.ini (931.00B)
|---- layout_543b56fd-a129-900d-8cbf-2769cd584b25.xml (4.76KB)
|---- Logo.png (44.25KB)
|---- MicrosoftGame.config (1.39KB)
|---- NitroxLauncher.exe (9.90MB)
|---- NitroxLauncher.exe.config (2.16KB)
|---- NitroxLauncher.pdb (141.50KB)
|---- NitroxServer-Subnautica.exe (48.00KB)
|---- NitroxServer-Subnautica.exe.config (1.21KB)
|---- NitroxServer-Subnautica.pdb (131.50KB)
|---- Patch Notes.txt (15.66KB)
|---- path.txt (27.00B)
|---- qmodmanager_log-Subnautica.txt (6.36KB)
|---- README.txt (355.00B)
|---- SmallLogo.png (4.81KB)
|---- Splash.png (4.60MB)
|---- StoreLogo.png (20.39KB)
|---- Subnautica.exe (636.50KB)
|---- Subnautica32.exe (68.50KB)
|---- unins000.dat (27.02KB)
|---- unins000.exe (3.00MB)
|---- UnityCrashHandler64.exe (1.04MB)
|---- UnityPlayer.dll (24.69MB)
|---- winhttp.dll (23.50KB)
[QModManager:INFO] Game Folder structure ended.
[QModManager:ERROR] There was an error while trying to apply Harmony patches.
[QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 01000023 (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Utility.Logger.Debug (System.String msg) [0x00000] in <972b42bb43bc4242992a67a147d9748d>:0 
  at QModManager.Patching.Patcher.PatchHarmony () [0x00000] in <972b42bb43bc4242992a67a147d9748d>:0
[QModManager:FATAL] An unhandled exception has been caught! Patching ended prematurely!
[QModManager:ERROR] System.TypeLoadException: Could not load type of field 'QModManager.Utility.Config:serializer' (3) due to: Could not resolve type with token 01000023 (from typeref, class/assembly Oculus.Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null type:Oculus.Newtonsoft.Json.JsonSerializer member:(null) signature:<none>
  at QModManager.Checks.VersionCheck.Check () [0x00000] in <972b42bb43bc4242992a67a147d9748d>:0 
  at QModManager.Patching.Patcher.Patch () [0x0022f] in <972b42bb43bc4242992a67a147d9748d>:0
[Warning: QMMLoader] QModsToLoad is null!
[Message:   BepInEx] Chainloader startup complete
Initializing Windows Store services
XGRuntime initialized successfully.
Starting AddUser...
Adding default user silently...
OnQuit behaviour queued for deferred registering, platform services aren't initialized.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 3693.
Total: 21.553900 ms (FindLiveObjects: 0.517800 ms CreateObjectMapping: 0.193400 ms MarkObjects: 20.821400 ms  DeleteObjects: 0.020700 ms)
Result returned from XUserAddAsync: 0x00000000
Sign in silently complete
GetId returned code: 0x00000000
Starting XBLive services...
Starting GetAchievements...
Getting Unlocked Achievements
Setting current user...
Material doesn't have a texture property '_MainTex'
Material doesn't have a texture property '_MainTex'
UserStorageXSave: User not signed in...
Save data init failed (NotSignedIn)
AddressablesUtility.LoadSceneAsync loading scene: MenuEnvironment in mode Additive
Telemetry session started.
Get achievements completed with result: 0x00000000
Extracted achievements with result: 0x00000000
12 achievements retrieved
OnAchievementsChanged event is null...
UserStorageXSave: User not signed in...
Save data init failed (NotSignedIn)
Curl error 51: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_CN_MISMATCH
error sending request to sentry: Unknown Error
UserStorageXSave: User not signed in...
Save data init failed (NotSignedIn)
AddressablesUtility.LoadSceneAsync loading scene: XMenu in mode Additive
Process name: Subnautica
changeset 68020, QualityLevel = 0
OK Running Win64
Application version: 68020
SystemInfo: 
 deviceModel = Nitro AN515-55 (Acer)
 deviceName = LAPTOP-4DMMO3TM
 deviceType = Desktop
 deviceUniqueIdentifier = 72fa1eaea179810ba87681a949adb0228fb43c46
 graphicsDeviceID = 8089
 graphicsDeviceName = NVIDIA GeForce GTX 1650
 graphicsDeviceType = Direct3D11
 graphicsDeviceVendor = NVIDIA
 graphicsDeviceVendorID = 4318
 graphicsDeviceVersion = Direct3D 11.0 [level 11.1]
 graphicsMemorySize = 3962
 graphicsShaderLevel = 50
 npotSupport = Full
 maxTextureSize = 16384
 operatingSystem = Windows 10  (10.0.0) 64bit
 processorCount = 8
 processorFrequency = 2496
 processorType = Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
 supportedRenderTargetCount = 8
 supports3DTextures = True
 supportsAccelerometer = False
 supportsComputeShaders = True
 supportsGyroscope = False
 supportsImageEffects = True
 supportsInstancing = True
 supportsLocationService = False
 supportsRawShadowDepthSampling = True
 supportsRenderTextures = True
 supportsRenderToCubemap = True
 supportsShadows = True
 supportsSparseTextures = True
 supportsStencil = 1
 supportsVibration = False
 systemMemorySize = 8023
Setting up 4 worker threads for Enlighten.
Thread -> id: 1188 -> priority: 1
Thread -> id: 3e14 -> priority: 1
Thread -> id: 5738 -> priority: 1
Thread -> id: 5364 -> priority: 1
Failed to deregister behaviour. GUIScaleManager instance not found.
Failed to deregister behaviour. GUIScaleManager instance not found.

**Comment by MagicJungle7053** [comment]
Btw I deleted Nitrox

**Comment by desperationfighter** [comment]
QMod and Nitrox do not work together in some cases QMod even has issue to start up after removing Nitrox as Nitrox interact with some files. 
[QModManager:ERROR] There was an error while trying to apply Harmony patches.
that can be an indicator. So ist tend to be more an external Error than a Bug.
The best you can do are this 2 Steps:

1. Reverify the Game -> as you are using MSStore version its sadly the best to redump it. (pro tip just make a backup copy next time so you can may switch between Nitrox/Qmod/Vanilla if you wish).

2. the MSStore version is ahead of time. There is currently no QMod Stable release for that. So in case you Error is continues you can try the eperimental Version that fixes some issues for MSStore Version. Download -> https://github.com/SubnauticaModding/QModManager/releases -> SN.EXP

If you still encounter any error i recommen to visit the Modding Discord: discord.gg/upwuwwq

**Comment by MagicJungle7053** [comment]
Thanks man good day.

**Comment by MagicJungle7053** [comment]
Now I get this:

Fallback handler could not load library C:/Users/Riley/Desktop/DUMP/Subnautica_Data/Mono/data-000001E4A8FD2040.dll
Fallback handler could not load library C:/Users/Riley/Desktop/DUMP/Subnautica_Data/Mono/data-000001E4A4556040.dll
Initialize engine version: 2019.4.9f1 (636)
[Subsystems] Discovering subsystems at path C:/Users/Riley/Desktop/DUMP/Subnautica_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version:  Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f99)
Vendor:
VRAM:     3962 MB
Driver:   30.0.14.9729
Begin MonoManager ReloadAssembly
- Completed reload, in  0.112 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed 
(Filename:  Line: 369)
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"! 
(Filename:  Line: 1889)
UnloadTime: 0.663100 ms

[Message:   BepInEx] BepInEx 5.4.15.0 - Subnautica (06/01/2022 19:00:57)
[Info   :   BepInEx] Running under Unity v2019.4.9.636
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.15.0]
[Warning:   BepInEx] Shimming C:\Users\Riley\Desktop\DUMP\BepInEx\patchers\BepInEx.MultiFolderLoader.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MultiFolderLoader 1.3.1.0]
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.OculusNewtonsoftRedirect 4.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.3.0.0]
[Info   :   BepInEx] 6 patcher plugins loaded
[Info   :MultiFolderLoader] Loading preloader patchers from mod
[Info   :MultiFolderLoader] Loading 0 preloader patchers from mods...
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [Assembly-CSharp] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Newtonsoft.Json] with [QModManager.OculusNewtonsoftRedirect]
[Info   :QModPluginGenerator] Loading QMMAssemblyCache...
[Info   :QModPluginGenerator] Could not find QMMAssemblyCache, skipping load.
[Info   :QModPluginGenerator] Clearing BepInEx cache...
[Info   :QModPluginGenerator] Cleared BepInEx cache in 8 ms.
[Info   :QModPluginGenerator] Saving QMMAssemblyCache...
[Info   :QModPluginGenerator] QMMAssemblyCache saved in 125 ms.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :MultiFolderLoader] Finding plugins from mods...
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [QModManager.LogFilter 4.3.0]
[Info   :   BepInEx] Loading [QMMLoader 4.3.0]
[QModManager:INFO] Detected game: Subnautica
[QModManager:INFO] Game Version: 68020 Build Date: 01-January-0001
[QModManager:INFO] Loading QModManager v4.3 built for Subnautica v68186...
[QModManager:INFO] Today is 06-January-2022_19:11:13
[QModManager:FATAL] A fatal error has occurred. An invalid game version was detected!
[QModManager:FATAL] A fatal patching exception has been caught! Patching ended prematurely!
[QModManager:ERROR] QModManager.Patching.FatalPatchingException: An invalid game version was detected!
  at QModManager.Patching.GameDetector..ctor () [0x00188] in <a979c4ae7ef041239f6fb0192915be25>:0 
  at QModManager.Patching.Patcher.Patch () [0x00012] in <a979c4ae7ef041239f6fb0192915be25>:0
[Message:   BepInEx] Chainloader startup complete
AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single
Unloading 4 Unused Serialized files (Serialized files now loaded: 9)
UnloadTime: 4.147600 ms
Initializing Windows Store services
XGRuntime initialized successfully.
Starting AddUser...
Adding default user silently...
OnQuit behaviour queued for deferred registering, platform services aren't initialized.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 3693.
Total: 23.000800 ms (FindLiveObjects: 0.471100 ms CreateObjectMapping: 0.216400 ms MarkObjects: 22.290300 ms  DeleteObjects: 0.022600 ms)
OnQuit behaviour queued for deferred registering, platform services aren't initialized.
Material doesn't have a texture property '_MainTex'
Material doesn't have a texture property '_MainTex'
AddressablesUtility.LoadSceneAsync loading scene: MenuEnvironment in mode Additive
Result returned from XUserAddAsync: 0x00000000
Sign in silently complete
GetId returned code: 0x00000000
Starting XBLive services...
Starting GetAchievements...
Getting Unlocked Achievements
Setting current user...
[QModManager:INFO] Finished loading QModManager. Loaded 0 mods.
UserStorageXSave: User not signed in...
Save data init failed (NotSignedIn)
Curl error 51: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_CN_MISMATCH
error sending request to sentry: Unknown Error
Telemetry session started.
Get achievements completed with result: 0x00000000
Extracted achievements with result: 0x00000000
12 achievements retrieved
OnAchievementsChanged event is null...
AddressablesUtility.LoadSceneAsync loading scene: XMenu in mode Additive
Process name: Subnautica
changeset 68020, QualityLevel = 0
OK Running Win64
Application version: 68020
SystemInfo: 
 deviceModel = Nitro AN515-55 (Acer)
 deviceName = LAPTOP-4DMMO3TM
 deviceType = Desktop
 deviceUniqueIdentifier = 72fa1eaea179810ba87681a949adb0228fb43c46
 graphicsDeviceID = 8089
 graphicsDeviceName = NVIDIA GeForce GTX 1650
 graphicsDeviceType = Direct3D11
 graphicsDeviceVendor = NVIDIA
 graphicsDeviceVendorID = 4318
 graphicsDeviceVersion = Direct3D 11.0 [level 11.1]
 graphicsMemorySize = 3962
 graphicsShaderLevel = 50
 npotSupport = Full
 maxTextureSize = 16384
 operatingSystem = Windows 10  (10.0.0) 64bit
 processorCount = 8
 processorFrequency = 2496
 processorType = Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
 supportedRenderTargetCount = 8
 supports3DTextures = True
 supportsAccelerometer = False
 supportsComputeShaders = True
 supportsGyroscope = False
 supportsImageEffects = True
 supportsInstancing = True
 supportsLocationService = False
 supportsRawShadowDepthSampling = True
 supportsRenderTextures = True
 supportsRenderToCubemap = True
 supportsShadows = True
 supportsSparseTextures = True
 supportsStencil = 1
 supportsVibration = False
 systemMemorySize = 8023

**Comment by desperationfighter** [comment]
[QModManager:FATAL] A fatal error has occurred. An invalid game version was detected!
yeah that the problem of Step 2 i mentioned before. Something is broken currently between MSStore version and QMod.
I don't thing i can help on that. (Feel free to test Stable QMod Version again or a other SN.EXP Version if available) 
Maybe somebody of the QMod devs can help
I guess you need to wait a bit for feedback on that.

**Comment by desperationfighter** [comment]
hey, short info for you. I just got a internal feedback that you should try the " QModManager_BZ.STABLE" (Below Zero) Version of qmod from the Release page.
You normally not supposte to do that. But it seems there is currently a pretty special case with that MSStore Update to be completly out of sync with everything.

**Comment by MagicJungle7053** [comment]
BZ doesn't work now I get this:

Fallback handler could not load library C:/Users/Riley/Desktop/DUMP/Subnautica_Data/Mono/data-000002319BB72040.dll
Fallback handler could not load library C:/Users/Riley/Desktop/DUMP/Subnautica_Data/Mono/data-0000023197378010.dll
Initialize engine version: 2019.4.9f1 (636)
[Subsystems] Discovering subsystems at path C:/Users/Riley/Desktop/DUMP/Subnautica_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version:  Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f99)
Vendor:
VRAM:     3962 MB
Driver:   30.0.14.9729
Begin MonoManager ReloadAssembly
- Completed reload, in  0.227 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed 
(Filename:  Line: 369)
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_HmdNotFoundPresenceFailed: "Hmd Not Found Presence Failed (126)"! 
(Filename:  Line: 1889)
UnloadTime: 0.895600 ms

[Message:   BepInEx] BepInEx 5.4.15.0 - Subnautica (06/01/2022 20:50:47)
[Info   :   BepInEx] Running under Unity v2019.4.9.636
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.15.0]
[Warning:   BepInEx] Shimming C:\Users\Riley\Desktop\DUMP\BepInEx\patchers\BepInEx.MultiFolderLoader.dll to use older version of Harmony (0Harmony20). Please update the plugin if possible.
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MultiFolderLoader 1.3.1.0]
[Info   :   BepInEx] Loaded 1 patcher method from [MirrorInternalLogs 1.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.OculusNewtonsoftRedirect 4.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.QModPluginGenerator 4.3.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [QModManager.UnityAudioFixer 4.3.0.0]
[Info   :   BepInEx] 6 patcher plugins loaded
[Info   :MultiFolderLoader] Loading preloader patchers from mod
[Info   :MultiFolderLoader] Loading 0 preloader patchers from mods...
[Info   :UnityAudioFixer] Attempting to enable Unity audio...
[Info   :UnityAudioFixer] Unity audio enabled.
[Info   :   BepInEx] Patching [Assembly-CSharp] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Newtonsoft.Json] with [QModManager.OculusNewtonsoftRedirect]
[Info   :QModPluginGenerator] Loading QMMAssemblyCache...
[Info   :QModPluginGenerator] Could not find QMMAssemblyCache, skipping load.
[Info   :QModPluginGenerator] Clearing BepInEx cache...
[Info   :QModPluginGenerator] Cleared BepInEx cache in 3 ms.
[Info   :QModPluginGenerator] Saving QMMAssemblyCache...
[Info   :QModPluginGenerator] QMMAssemblyCache saved in 50 ms.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :MultiFolderLoader] Finding plugins from mods...
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [QModManager.LogFilter 4.3.0]
[Info   :   BepInEx] Loading [QMMLoader 4.3.0]
[QModManager:INFO] Detected game: Subnautica
[QModManager:INFO] Game Version: 68020 Build Date: 01-January-0001
[QModManager:INFO] Loading QModManager v4.3...
[QModManager:INFO] Today is 06-January-2022_21:00:59
[QModManager:FATAL] A fatal error has occurred. An invalid game version was detected!
[QModManager:FATAL] A fatal patching exception has been caught! Patching ended prematurely!
[QModManager:ERROR] QModManager.Patching.FatalPatchingException: An invalid game version was detected!
  at QModManager.Patching.GameDetector..ctor () [0x00188] in <a80bae7503294a8684380787b5c5d1d2>:0 
  at QModManager.Patching.Patcher.Patch () [0x00012] in <a80bae7503294a8684380787b5c5d1d2>:0
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type SpriteManager and name OnLoadedSpriteAtlases and parameters
NullReferenceException: Null method for QModManager.QMMLoader
  at HarmonyLib.PatchProcessor.Patch () [0x0001d] in <48ac0133328b486983afe98eee5b730e>:0 
  at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator) [0x00031] in <48ac0133328b486983afe98eee5b730e>:0 
  at QModInstaller.BepInEx.Plugins.QMMLoader.PreInitializeQMods () [0x00089] in <a80bae7503294a8684380787b5c5d1d2>:0 
  at QModInstaller.BepInEx.Plugins.QMMLoader.Awake () [0x00046] in <a80bae7503294a8684380787b5c5d1d2>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
PreStartScreen:Start()
[Message:   BepInEx] Chainloader startup complete
AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single
Unloading 4 Unused Serialized files (Serialized files now loaded: 9)
UnloadTime: 3.394000 ms
Initializing Windows Store services
XGRuntime initialized successfully.
Starting AddUser...
Adding default user silently...
OnQuit behaviour queued for deferred registering, platform services aren't initialized.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 3693.
Total: 29.375700 ms (FindLiveObjects: 0.407100 ms CreateObjectMapping: 0.202700 ms MarkObjects: 28.721100 ms  DeleteObjects: 0.044400 ms)
OnQuit behaviour queued for deferred registering, platform services aren't initialized.
Material doesn't have a texture property '_MainTex'
Material doesn't have a texture property '_MainTex'
AddressablesUtility.LoadSceneAsync loading scene: MenuEnvironment in mode Additive
NullReferenceException: Object reference not set to an instance of an object
  at PlatformUtils.GetCurrentUserId () [0x0000a] in <bd4a497d7a88481684e38389edab3afc>:0 
  at uGUI_FeedbackCollector.GetPlayerOnlineId () [0x00016] in <bd4a497d7a88481684e38389edab3afc>:0 
  at uGUI_FeedbackCollector+<RepliesRoutine>d__63.MoveNext () [0x00076] in <bd4a497d7a88481684e38389edab3afc>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <eaf013c1c79547e4ab1bcad4b98f0f4d>:0
Result returned from XUserAddAsync: 0x00000000
Sign in silently complete
GetId returned code: 0x00000000
Starting XBLive services...
Starting GetAchievements...
Getting Unlocked Achievements
Setting current user...
UserStorageXSave: User not signed in...
Save data init failed (NotSignedIn)
AddressablesUtility.LoadSceneAsync loading scene: XMenu in mode Additive
Process name: Subnautica
changeset 68020, QualityLevel = 0
OK Running Win64
Application version: 68020
SystemInfo: 
 deviceModel = Nitro AN515-55 (Acer)
 deviceName = LAPTOP-4DMMO3TM
 deviceType = Desktop
 deviceUniqueIdentifier = 72fa1eaea179810ba87681a949adb0228fb43c46
 graphicsDeviceID = 8089
 graphicsDeviceName = NVIDIA GeForce GTX 1650
 graphicsDeviceType = Direct3D11
 graphicsDeviceVendor = NVIDIA
 graphicsDeviceVendorID = 4318
 graphicsDeviceVersion = Direct3D 11.0 [level 11.1]
 graphicsMemorySize = 3962
 graphicsShaderLevel = 50
 npotSupport = Full
 maxTextureSize = 16384
 operatingSystem = Windows 10  (10.0.0) 64bit
 processorCount = 8
 processorFrequency = 2496
 processorType = Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
 supportedRenderTargetCount = 8
 supports3DTextures = True
 supportsAccelerometer = False
 supportsComputeShaders = True
 supportsGyroscope = False
 supportsImageEffects = True
 supportsInstancing = True
 supportsLocationService = False
 supportsRawShadowDepthSampling = True
 supportsRenderTextures = True
 supportsRenderToCubemap = True
 supportsShadows = True
 supportsSparseTextures = True
 supportsStencil = 1
 supportsVibration = False
 systemMemorySize = 8023
Saving game settings
OpenOrCreateContainer returned null
Curl error 51: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_CN_MISMATCH
error sending request to sentry: Unknown Error
Telemetry session started.
Get achievements completed with result: 0x00000000
Extracted achievements with result: 0x00000000
12 achievements retrieved
OnAchievementsChanged event is null...

**Comment by MagicJungle7053** [comment]
Any Info about MSStore

**Comment by Metious** [comment]
From the QModManager releases, install QModManager 4.2.1 Experimental branch. But before doing so, make sure to delete your BepInEx folder

**Comment by MagicJungle7053** [comment]
now i cant create saves tho the modding works

**Comment by MagicJungle7053** [comment]
Found the issue for saving but sml brocken :(

**Comment by Metious** [comment]
Install [SMLHelper 2.11.1_SN1.EXP](https://github.com/SubnauticaModding/SMLHelper/releases/download/v2.11.1/SMLHelper_SN.EXP.zip) and it should work.
Also, you have noticed that it takes us quite a bit to answer on GitHub, so i recommend you asking for help in our [Subnautica Modding Discord Server](https://discord.gg/UpWuWwq) next time.
