### ISSUE TITLE
QMods folder missing.

### ISSUE THREAD

**Issue by unique2424** [SubnauticaModding/QModManager#285]
Why QMods folder is missing? 
![Screenshot 2022-11-08 141732](https://user-images.githubusercontent.com/75830672/200489403-a02a0e6a-8bb3-4ae8-8b29-feb4103e4bc3.png)

**Comment by desperationfighter** [comment]
Because things happened...
Humans are not Perfect.

And in case that was not your question.
The Folder was empty anyway.
You can create it yourself or startup the Game once after installing QMM and the Folder will be created automatically.
