### ISSUE TITLE
Version 4.4.4 does not run, 4.3 works fine - MSStore custom install directory

### ISSUE THREAD

**Issue by SayuShira** [SubnauticaModding/QModManager#286]
**Describe the problem**
Version 4.4.4 does not work with Subnautica installed in a custom location via MSStore (or actually in my case GamePass).
Something fails with preload/harmony patches. You can read more out of the log files than me tho.
There is no error message at all. The mod settings simply never appear in the menu.

Version 4.3 ( QModManager_SN.STABLE.zip ) does work apparently so I will use this version for now- thanks for keeping them available :pray:

**Screenshots / Logs**
These are the two log files I spotted.
Going by the first line of the `qmodmanager_log-Subnautica.txt`, my guess was that it tried to find the game in the default app install folder for whatever reason, instead of the game folder I placed the files in.  
I chose to use a custom location for games tho~  
Subnautica.exe is in `D:\Games\Subnautica\Content` installed via Xbox App.

[qmodmanager_log-Subnautica.txt](https://github.com/SubnauticaModding/QModManager/files/9985807/qmodmanager_log-Subnautica.txt)
[LogOutput.log](https://github.com/SubnauticaModding/QModManager/files/9985808/LogOutput.log)

**Additional info**
I can probably provide extra info if you need something. Not sure what is necessary right now.
This is my first look into Subnautica mods, please spare me some mistakes.
OS: Win 11 22H2
GPU driver is up-to-date

**Comment by ramennoodlesxv** [comment]
Can you please join the [Subnautica Modding](https://discord.gg/UpWuWwq) discord server
I don't believe it's possible your game is working on 4.4.3, and if it is, I'd like to know how, so @ me after you join
@RamuneNeptune#1816

**Comment by SayuShira** [comment]
Thanks for the fast response.
I sadly had to discover that some mods might not work- e.g. map mod. But the game started and mods showed in the mod settings tab after downgrading to 4.3. The map mod let the game freeze right after loading in.
At least loading and running around a bit worked with the mods listed in the image. No long test session yet tho!

I didn't do anything but drag the content of the v4.3 download into the Subnautica folder, it started with the mod menu visible and mods seem to be loading (more quick slots could be seen and I could move my fish to slots 6 to =).
[qmodmanager_log-Subnautica.txt](https://github.com/SubnauticaModding/QModManager/files/9986143/qmodmanager_log-Subnautica.txt)
[LogOutput.log](https://github.com/SubnauticaModding/QModManager/files/9986148/LogOutput.log)

Sorry for the delay this will cause, but I will only ping you tomorrow. I joined the Discord server for now, but it's very late over here and I need to sleep first.
But a quick look at the first log looks like you might have a point that it's uhhhh not exactly "working as intended". More tomorrow in Discord then.
![image](https://user-images.githubusercontent.com/104025906/201252223-ba968588-7227-441f-9b47-fc6ed8c9f591.png)

**Comment by SayuShira** [comment]
Thanks for your help in Discord!
For reference: Game leave Gamepass soon anyway. Gamepass doesn't run with all mods. To work you want QMod 4.2.1 EXP and SMLHelper 2.11.1, as per Ramune's guide.

Closing this then- sorry for the false report.
