### ISSUE TITLE
QModManager 4.4.4 not compatible with current Subnautica.

### ISSUE THREAD

**Issue by Berserker66** [SubnauticaModding/QModManager#288]
**Describe the bug**

Fails to initialize.

**Screenshots**

**Additional info**

"Subnautica Living Large Update" released.

**Comment by desperationfighter** [comment]
So you do not even give People time to update QMM ? We are fully aware of that issue but we can not magical provice a fix that fast.

**Comment by Berserker66** [comment]
Indeed I do not, and released an update to my mod without QModManager https://github.com/Berserker66/ArchipelagoSubnauticaModSrc/releases

**Comment by PrimeSonic** [comment]
Don't know if you were trying to be coy or not with that answer.
But take a second to compare the amount of code in your own repo to the amount of code being maintained by the team.
https://github.com/SubnauticaModding
I _think_ you'll begin to see why it would take longer to update the core libraries than it does a single mod.

Closing this issue as
1. no useful info has been provided that would assist and
2. the team is already aware and working on it

**Comment by georgehank** [comment]
PrimeSonic: you don't close bugs just because it's a known issue.  You close bugs when they're actually fixed.  Most devs would not welcome this bug either, _because they'd have logged such a bug [as a reminder] themselves_
