### ISSUE TITLE
Support Steam Deck by including a notice for required settings

### ISSUE THREAD

**Issue by Morpheus0x** [SubnauticaModding/QModManager#290]
**Describe the issue**
Following the normal install instructions on the Steam Deck isn't sufficient to getting mods running. It is required to add the following steam launch option to Subnautica (Below Zero):
`WINEDLLOVERRIDES="winhttp.dll=n,b" %command%`

Please add this to any description or install instruction page.

**Comment by Metious** [comment]
This is already the solution we're recommending to Linux folks at #173.

Can you provide a link to the instructions you're referring to?

**Comment by Morpheus0x** [comment]
I googled if there are any issues with bepinex on steamdeck and found this reddit post with the correct command in the comments: https://www.reddit.com/r/SteamDeck/comments/wj2n7l/comment/ilpn2kd/

**Comment by Metious** [comment]
Included our Linux guide in NexusMods and Submodica pages of QMM.
