### ISSUE TITLE
QModManager 3.0 - Roadmap

### ISSUE THREAD

**Issue by AlexejheroYTB** [SubnauticaModding/QModManager#98]
## Required

<details>
<summary>Pass-through DLL</summary>

![image](https://user-images.githubusercontent.com/32238504/58628442-5f069f00-82e2-11e9-88b2-61308d251a84.png)

</details>

<details>
<summary>Documentation</summary>

- Wiki
- Assembly Publicizer notice
- README

</details>

<details>
<summary>Fix <code>Open Log</code> button for MacOS</summary>

![image](https://user-images.githubusercontent.com/32238504/58630832-43eb5d80-82e9-11e9-9ce5-f040bb50aa99.png)

</details>

## Optional

<details>
<summary>Prevent saves from being loaded if mods are missing</summary>

![image](https://user-images.githubusercontent.com/32238504/61176213-8b8e2600-a5c5-11e9-8d4b-7e4a8f571abc.png)

</details>

<details>
<summary>Add new and expand capabilities of <code>Spawnable</code> classes</summary>

![image](https://user-images.githubusercontent.com/32238504/58628502-865d6c00-82e2-11e9-929d-4fbf728cb6a9.png)
![image](https://user-images.githubusercontent.com/32238504/58628518-907f6a80-82e2-11e9-8e44-55363d48ed16.png)

</details>

<details>
<summary><code>&lt;TechType&gt;.ToString</code></summary>

![image](https://user-images.githubusercontent.com/32238504/58628685-14395700-82e3-11e9-94ec-a69ee9e1e921.png)

</details>

<details>
<summary>Cache system re-write</summary>

![image](https://user-images.githubusercontent.com/32238504/58628720-2915ea80-82e3-11e9-9f88-4f61f5c8abac.png)

</details>

<details>
<summary>Add <code>PrefabIdentifier</code> to all <code>ModPrefab</code>s</summary>

![image](https://user-images.githubusercontent.com/32238504/58629195-75155f00-82e4-11e9-90c0-63fb7970fc1d.png)

</details>

<details>
<summary><code>&lt;PDAItem&gt;.UnlockedBy</code></summary>

![image](https://user-images.githubusercontent.com/32238504/58629239-94ac8780-82e4-11e9-890d-5b105aa1d15d.png)

</details>

<details>
<summary>Proxy DLL</summary>

With the engine update to 2018, you can guarantee that there will be users trying to install QModManager 3.0 for cracked versions not yet on U2018.

I suggest turning QModInstaller.dll intro a proxy file which checks for the unity version, nitrox, and does all initializing before QModManager.dll is loaded into the app domain.

</details>

**Comment by PrimeSonic** [comment]
### Potential new abstract child classes
##### Spawnable child classes
- Harvestable : Based on Harvest methods in [CraftDataHandler](https://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs)
- Edible : Based on [CustomFoodPrefab](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/CustomCraftSML/SMLHelperItems/CustomFoodPrefab.cs) from CC2
##### Buildable child classes
- Crafter : Based on [CustomFabricatorBuildable](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/CustomCraftSML/SMLHelperItems/CustomFabricatorBuildable.cs) from CC2 and crafting tree methods from [CraftTreeHandler](https://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Handlers/CraftTreeHandler.cs)
##### Craftable child classes
- Equipable : Base on ideas from [MoreCyclopsUpgrades](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/MoreCyclopsUpgrades/Modules/CyclopsModule.cs) and [UpgradedVehicles](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/UpgradedVehicles/Craftables/SpeedBooster.cs)
### Potential new virtual properties
##### Properties on Spawnable
- Inventory item size : Based on item size method in [CraftDataHandler](https://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs)
  - Would go hand in hand with an "IsPickupable" property similar to the [CustomFishPrefab](https://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Assets/CustomFishPrefab.cshttps://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Assets/CustomFishPrefab.cs)
##### Properties on Craftable
- Crafting time : Based on crafting time methods in [CraftDataHandler](https://github.com/QModManager/QModManager/blob/dev/merge/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs)

**Comment by PrimeSonic** [comment]
We should include a standardized way of locking blueprints behind encyclopedia entries.  
@kylinator25 proved this to be possible with the Alien Rifle.

The only problem to sort out with this is that these blueprints remain locked when playing in Creative mode or when using the "unlock all" command.

**Comment by PrimeSonic** [comment]
Moved relevant points back to the SMLHelper repo  
https://github.com/SubnauticaModding/SMLHelper/issues/118
